import { AppError } from '../../../core/errors/app-error.js';
import { escapeHtml, escapeXml, safeFilename } from '../domain/render-utils.js';
export class DocumentService {
    sales;
    purchases;
    catalog;
    customers;
    suppliers;
    settings;
    organization;
    pdf;
    constructor(sales, purchases, catalog, customers, suppliers, settings, organization, pdf) {
        this.sales = sales;
        this.purchases = purchases;
        this.catalog = catalog;
        this.customers = customers;
        this.suppliers = suppliers;
        this.settings = settings;
        this.organization = organization;
        this.pdf = pdf;
    }
    async salePrint(t, id) { const sale = await this.sales.get(t, id); if (!sale)
        throw new AppError('SALE_NOT_FOUND', 'فاتورة البيع غير موجودة', 404); const [meta, customer, products] = await Promise.all([this.meta(t, sale.branchId), sale.customerId ? this.customers.get(t, sale.customerId) : Promise.resolve(null), this.productMap(t, sale.lines.map(x => x.productId))]); const rows = sale.lines.map((l, i) => `<tr><td>${i + 1}</td><td>${escapeHtml(products.get(l.productId) ?? l.productId)}</td><td>${fmt(l.quantity)}</td><td>${money(l.unitPrice, meta.currency)}</td><td>${money(l.discount, meta.currency)}</td><td>${money(l.tax, meta.currency)}</td><td>${money(l.net, meta.currency)}</td></tr>`).join(''); return this.htmlDoc(`فاتورة بيع ${sale.number}`, `فاتورة بيع`, sale.number, meta, customer?.name ?? 'عميل نقدي', sale.createdAt, `<table><thead><tr><th>#</th><th>الصنف</th><th>الكمية</th><th>السعر</th><th>الخصم</th><th>الضريبة</th><th>الإجمالي</th></tr></thead><tbody>${rows}</tbody></table>${totals([['الإجمالي قبل الخصم', sale.subtotal], ['الخصم الكلي', sale.discount], ...(sale.loyaltyDiscount > 0 ? [['خصم نقاط الولاء', sale.loyaltyDiscount]] : []), ['الضريبة', sale.tax], ['الإجمالي النهائي', sale.total]], meta.currency)}${sale.loyaltyPointsRedeemed || sale.loyaltyPointsEarned ? `<section class="party"><b>الولاء:</b> استبدال ${fmt(sale.loyaltyPointsRedeemed)} نقطة • اكتساب ${fmt(sale.loyaltyPointsEarned)} نقطة</section>` : ''}`); }
    async salePdf(t, id) { const sale = await this.sales.get(t, id); if (!sale)
        throw new AppError('SALE_NOT_FOUND', 'فاتورة البيع غير موجودة', 404); const html = await this.salePrint(t, id); const content = await this.pdf.renderHtml(String(html.content)); return { content, contentType: 'application/pdf', filename: safeFilename(`فاتورة بيع - ${sale.number}.pdf`) }; }
    async saleExcel(t, id) { const sale = await this.sales.get(t, id); if (!sale)
        throw new AppError('SALE_NOT_FOUND', 'فاتورة البيع غير موجودة', 404); const meta = await this.meta(t, sale.branchId), products = await this.productMap(t, sale.lines.map(x => x.productId)); const rows = [['رقم الفاتورة', sale.number], ['التاريخ', new Date(sale.createdAt).toISOString()], ['الفرع', meta.branchName], [], ['الصنف', 'الكمية', 'سعر الوحدة', 'الخصم', 'الضريبة', 'الإجمالي'], ...sale.lines.map(l => [products.get(l.productId) ?? l.productId, l.quantity, l.unitPrice, l.discount, l.tax, l.net]), [], ['خصم نقاط الولاء', '', '', '', '', sale.loyaltyDiscount], ['نقاط مستبدلة', '', '', '', '', sale.loyaltyPointsRedeemed], ['نقاط مكتسبة', '', '', '', '', sale.loyaltyPointsEarned], ['الإجمالي', '', '', '', '', sale.total]]; return this.excelDoc(`فاتورة بيع - ${sale.number}.xls`, 'فاتورة بيع', rows); }
    async purchasePrint(t, id) { const pur = await this.purchases.getReceipt(t, id); if (!pur)
        throw new AppError('PURCHASE_NOT_FOUND', 'فاتورة الشراء غير موجودة', 404); const [meta, supplier, products] = await Promise.all([this.meta(t, pur.branchId), this.suppliers.get(t, pur.supplierId), this.productMap(t, pur.lines.map(x => x.productId))]); const rows = pur.lines.map((l, i) => `<tr><td>${i + 1}</td><td>${escapeHtml(products.get(l.productId) ?? l.productId)}</td><td>${fmt(l.quantity)}</td><td>${money(l.unitCost, meta.currency)}</td><td>${escapeHtml(l.batchNo ?? '—')}</td><td>${escapeHtml(l.expiryDate ?? '—')}</td><td>${money(l.quantity * l.unitCost, meta.currency)}</td></tr>`).join(''); return this.htmlDoc(`فاتورة شراء ${pur.number}`, 'فاتورة شراء', pur.number, meta, supplier?.name ?? pur.supplierId, pur.createdAt, `<table><thead><tr><th>#</th><th>الصنف</th><th>الكمية</th><th>التكلفة</th><th>التشغيلة</th><th>الصلاحية</th><th>الإجمالي</th></tr></thead><tbody>${rows}</tbody></table>${totals([['الإجمالي', pur.total]], meta.currency)}`); }
    async purchasePdf(t, id) { const pur = await this.purchases.getReceipt(t, id); if (!pur)
        throw new AppError('PURCHASE_NOT_FOUND', 'فاتورة الشراء غير موجودة', 404); const html = await this.purchasePrint(t, id); const content = await this.pdf.renderHtml(String(html.content)); return { content, contentType: 'application/pdf', filename: safeFilename(`فاتورة شراء - ${pur.number}.pdf`) }; }
    async purchaseExcel(t, id) { const pur = await this.purchases.getReceipt(t, id); if (!pur)
        throw new AppError('PURCHASE_NOT_FOUND', 'فاتورة الشراء غير موجودة', 404); const meta = await this.meta(t, pur.branchId), products = await this.productMap(t, pur.lines.map(x => x.productId)); const rows = [['رقم الفاتورة', pur.number], ['التاريخ', new Date(pur.createdAt).toISOString()], ['الفرع', meta.branchName], [], ['الصنف', 'الكمية', 'التكلفة', 'التشغيلة', 'الصلاحية', 'الإجمالي'], ...pur.lines.map(l => [products.get(l.productId) ?? l.productId, l.quantity, l.unitCost, l.batchNo ?? '', l.expiryDate ?? '', l.quantity * l.unitCost]), [], ['الإجمالي', '', '', '', '', pur.total]]; return this.excelDoc(`فاتورة شراء - ${pur.number}.xls`, 'فاتورة شراء', rows); }
    async meta(t, branchId) { const [settings, tenant, branches] = await Promise.all([this.settings.get(t), this.organization.getTenant(t), this.organization.listBranches(t)]); const branch = branches.find(x => x.id === branchId); return { pharmacyName: settings?.pharmacyName ?? tenant?.name ?? 'Elhafez Pharmacy', phone: settings?.phone ?? null, address: settings?.address ?? null, footer: settings?.invoiceFooter ?? null, currency: tenant?.currency ?? 'EGP', branchName: branch?.name ?? branchId }; }
    async productMap(t, ids) { const unique = [...new Set(ids)], pairs = await Promise.all(unique.map(async (id) => [id, (await this.catalog.get(t, id))?.name ?? id])); return new Map(pairs); }
    htmlDoc(filename, title, no, meta, party, date, body) { const content = `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)} ${escapeHtml(no)}</title><style>${printCss}</style></head><body><main><header><div><h1>${escapeHtml(meta.pharmacyName)}</h1><p>${escapeHtml(meta.branchName)}</p><small>${escapeHtml(meta.phone ?? '')} ${escapeHtml(meta.address ?? '')}</small></div><div class="doc"><h2>${escapeHtml(title)}</h2><b>${escapeHtml(no)}</b><span>${escapeHtml(new Date(date).toLocaleString('ar-EG'))}</span></div></header><section class="party"><b>الطرف:</b> ${escapeHtml(party)}</section>${body}<footer>${escapeHtml(meta.footer ?? '')}<small>Powered by Elhafez Technology</small></footer></main><script>window.addEventListener('load',()=>{document.querySelector('#print')?.addEventListener('click',()=>window.print())})</script><button id="print" class="print">طباعة / حفظ PDF</button></body></html>`; return { content, contentType: 'text/html; charset=utf-8', filename: `${safeFilename(filename)}.html` }; }
    excelDoc(filename, sheetName, rows) { const xmlRows = rows.map(r => `<Row>${r.map(v => `<Cell><Data ss:Type="${typeof v === 'number' ? 'Number' : 'String'}">${escapeXml(v)}</Data></Cell>`).join('')}</Row>`).join(''); const content = `<?xml version="1.0" encoding="UTF-8"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="${escapeXml(sheetName)}"><Table>${xmlRows}</Table></Worksheet></Workbook>`; return { content, contentType: 'application/vnd.ms-excel; charset=utf-8', filename: safeFilename(filename) }; }
}
function fmt(v) { return new Intl.NumberFormat('ar-EG', { maximumFractionDigits: 3 }).format(v); }
function money(v, c) { try {
    return new Intl.NumberFormat('ar-EG', { style: 'currency', currency: c, maximumFractionDigits: 2 }).format(v);
}
catch {
    return `${fmt(v)} ${c}`;
} }
function totals(rows, currency) { return `<section class="totals">${rows.map(([l, v], i) => `<div class="${i === rows.length - 1 ? 'grand' : ''}"><span>${escapeHtml(l)}</span><b>${money(v, currency)}</b></div>`).join('')}</section>`; }
const printCss = `*{box-sizing:border-box}body{margin:0;font-family:Tahoma,Arial,sans-serif;background:#eef3f3;color:#173236}main{width:min(900px,calc(100% - 32px));margin:24px auto;background:white;padding:32px;box-shadow:0 10px 35px #0002}header{display:flex;justify-content:space-between;gap:20px;border-bottom:2px solid #075867;padding-bottom:18px}h1,h2,p{margin:0}h1{color:#075867}.doc{text-align:left;display:grid;gap:6px}.doc h2{color:#075867}.doc span,small{color:#718184}.party{padding:16px 0}.party b{color:#075867}table{width:100%;border-collapse:collapse}th,td{border:1px solid #dbe6e5;padding:9px;text-align:right;font-size:12px}th{background:#f0f7f6}.totals{margin:18px 0 0 auto;width:min(360px,100%);display:grid;gap:6px}.totals div{display:flex;justify-content:space-between;padding:7px 10px}.totals .grand{background:#075867;color:white;border-radius:8px;font-size:16px}footer{margin-top:30px;border-top:1px solid #dbe6e5;padding-top:15px;display:flex;justify-content:space-between;color:#718184}.print{position:fixed;left:18px;bottom:18px;border:0;border-radius:12px;background:#075867;color:#fff;padding:12px 18px;font-weight:bold}@media print{body{background:white}main{width:100%;margin:0;box-shadow:none;padding:8mm}.print{display:none}}`;
