import type { ReconciliationServiceDependencies } from '../contracts/dependencies';
'use strict';
module.exports=function create_reconciliation_service(ctx:ReconciliationServiceDependencies){
 const nowIso=(...args)=>ctx.nowIso(...args);


async function buildFinancialReconciliation(client:any,tid:any,branch:any=''){
 const args=[tid,String(branch||'')],issues:any[]=[],add=(type:any,severity:any,rows:any,meta:any={})=>{for(const row of rows||[]){const ref=String(row.ref||row.no||row.id||row.sale_no||row.purchase_no||'');issues.push({id:`${type}:${row.id||ref||issues.length}`,type,severity,reference:ref||null,date:row.at||row.created_at||row.updated_at||null,user:row.user_name||null,branch:row.branch_id||null,expected:row.expected??meta.expected??null,actual:row.actual??meta.actual??null,missing:row.missing||meta.missing||null,suggestedAction:row.suggested_action||meta.action||'مراجعة المستند والحركات المرتبطة قبل أي إجراء',repairAction:row.repair_action||meta.repairAction||'quarantine',entityStore:row.entity_store||meta.store||null,entityId:row.entity_id||row.id||null,details:row})}};
 const qs=await Promise.all([
  client.query(`SELECT r.id,r.data->>'no' no,r.data->>'at' at,r.data->>'userName' user_name,r.data->>'branchId' branch_id,'Stock Movement' missing FROM records r WHERE r.tenant_id=$1 AND r.store='sales' AND COALESCE(r.data->>'integrityStatus','')<>'quarantine' AND ($2='' OR COALESCE(r.data->>'branchId','')=$2) AND NOT EXISTS(SELECT 1 FROM records m WHERE m.tenant_id=r.tenant_id AND m.store='stockMoves' AND m.data->>'type'='sale' AND m.data->>'ref'=r.data->>'no') ORDER BY r.created_at DESC LIMIT 200`,args),
  client.query(`SELECT r.id,r.data->>'no' no,r.data->>'at' at,r.data->>'userName' user_name,r.data->>'branchId' branch_id,COALESCE(NULLIF(r.data->>'total','')::numeric,0) expected,COALESCE((SELECT SUM(COALESCE(NULLIF(c.data->>'amount','')::numeric,0)) FROM records c WHERE c.tenant_id=r.tenant_id AND c.store='cashMoves' AND c.data->>'type'='sale' AND c.data->>'ref'=r.data->>'no' AND c.data->>'direction'='in'),0) actual,'Cash Movement' missing FROM records r WHERE r.tenant_id=$1 AND r.store='sales' AND COALESCE(r.data->>'integrityStatus','')<>'quarantine' AND COALESCE(r.data->>'payment','') IN('cash','card','wallet','bank','split') AND ($2='' OR COALESCE(r.data->>'branchId','')=$2) AND abs(COALESCE(NULLIF(r.data->>'total','')::numeric,0)-COALESCE((SELECT SUM(COALESCE(NULLIF(c.data->>'amount','')::numeric,0)) FROM records c WHERE c.tenant_id=r.tenant_id AND c.store='cashMoves' AND c.data->>'type'='sale' AND c.data->>'ref'=r.data->>'no' AND c.data->>'direction'='in'),0))>0.01 ORDER BY r.created_at DESC LIMIT 200`,args),
  client.query(`SELECT r.id,r.data->>'no' no,r.data->>'at' at,r.data->>'userName' user_name,r.data->>'branchId' branch_id,'GL Entry' missing FROM records r WHERE r.tenant_id=$1 AND r.store='sales' AND COALESCE(r.data->>'integrityStatus','')<>'quarantine' AND ($2='' OR COALESCE(r.data->>'branchId','')=$2) AND NOT EXISTS(SELECT 1 FROM records j WHERE j.tenant_id=r.tenant_id AND j.store='journal' AND j.data->>'ref'=r.data->>'no' AND COALESCE(j.data->>'type','') LIKE 'sale%') ORDER BY r.created_at DESC LIMIT 200`,args),
  client.query(`SELECT r.id,r.data->>'no' no,r.data->>'at' at,r.data->>'userName' user_name,r.data->>'branchId' branch_id,'Audit' missing FROM records r WHERE r.tenant_id=$1 AND r.store='sales' AND COALESCE(r.data->>'integrityStatus','')<>'quarantine' AND ($2='' OR COALESCE(r.data->>'branchId','')=$2) AND NOT EXISTS(SELECT 1 FROM audit_logs a WHERE a.tenant_id=r.tenant_id AND (a.ref=r.id OR a.ref=r.data->>'no')) ORDER BY r.created_at DESC LIMIT 200`,args),
  client.query(`SELECT r.id,r.data->>'no' no,r.data->>'at' at,r.data->>'branchId' branch_id,'sale_documents_core projection' missing FROM records r LEFT JOIN sale_documents_core d ON d.tenant_id=r.tenant_id AND d.id=r.id WHERE r.tenant_id=$1 AND r.store='sales' AND COALESCE(r.data->>'integrityStatus','')<>'quarantine' AND ($2='' OR COALESCE(r.data->>'branchId','')=$2) AND d.id IS NULL ORDER BY r.created_at DESC LIMIT 200`,args),
  client.query(`SELECT d.id,d.no,d.at,d.branch_id,'authoritative sales record' missing,'sale_documents_core' entity_store,d.id entity_id,'clear_orphan_projection' repair_action FROM sale_documents_core d LEFT JOIN records r ON r.tenant_id=d.tenant_id AND r.store='sales' AND r.id=d.id WHERE d.tenant_id=$1 AND ($2='' OR COALESCE(d.branch_id,'')=$2) AND r.id IS NULL ORDER BY d.at DESC LIMIT 200`,args),
  client.query(`SELECT r.id,r.data->>'no' no,r.data->>'at' at,r.data->>'branchId' branch_id,'Stock Movement' missing FROM records r WHERE r.tenant_id=$1 AND r.store='purchases' AND COALESCE(r.data->>'integrityStatus','')<>'quarantine' AND ($2='' OR COALESCE(r.data->>'branchId','')=$2) AND NOT EXISTS(SELECT 1 FROM records m WHERE m.tenant_id=r.tenant_id AND m.store='stockMoves' AND m.data->>'type'='purchase' AND m.data->>'ref'=r.data->>'no') ORDER BY r.created_at DESC LIMIT 200`,args),
  client.query(`SELECT r.id,r.data->>'no' no,r.data->>'at' at,r.data->>'branchId' branch_id,COALESCE(NULLIF(r.data->>'paidNow','')::numeric,0) expected,COALESCE((SELECT SUM(COALESCE(NULLIF(c.data->>'amount','')::numeric,0)) FROM records c WHERE c.tenant_id=r.tenant_id AND c.store='cashMoves' AND c.data->>'type'='supplier_payment' AND c.data->>'ref'=r.data->>'no' AND c.data->>'direction'='out'),0) actual,'Cash Movement' missing FROM records r WHERE r.tenant_id=$1 AND r.store='purchases' AND COALESCE(r.data->>'integrityStatus','')<>'quarantine' AND COALESCE(NULLIF(r.data->>'paidNow','')::numeric,0)>0 AND COALESCE(r.data->>'paymentMethod','cash')<>'bank' AND ($2='' OR COALESCE(r.data->>'branchId','')=$2) AND abs(COALESCE(NULLIF(r.data->>'paidNow','')::numeric,0)-COALESCE((SELECT SUM(COALESCE(NULLIF(c.data->>'amount','')::numeric,0)) FROM records c WHERE c.tenant_id=r.tenant_id AND c.store='cashMoves' AND c.data->>'type'='supplier_payment' AND c.data->>'ref'=r.data->>'no' AND c.data->>'direction'='out'),0))>0.01 ORDER BY r.created_at DESC LIMIT 200`,args),
  client.query(`SELECT r.id,r.data->>'no' no,r.data->>'at' at,r.data->>'branchId' branch_id,'GL Entry' missing FROM records r WHERE r.tenant_id=$1 AND r.store='purchases' AND COALESCE(r.data->>'integrityStatus','')<>'quarantine' AND ($2='' OR COALESCE(r.data->>'branchId','')=$2) AND (NOT EXISTS(SELECT 1 FROM records j WHERE j.tenant_id=r.tenant_id AND j.store='journal' AND j.data->>'ref'=r.data->>'no' AND j.data->>'type'='purchase') OR (COALESCE(NULLIF(r.data->>'paidNow','')::numeric,0)>0 AND NOT EXISTS(SELECT 1 FROM records j WHERE j.tenant_id=r.tenant_id AND j.store='journal' AND j.data->>'ref'=(r.data->>'no')||'-PAY' AND j.data->>'type'='supplier_payment'))) ORDER BY r.created_at DESC LIMIT 200`,args),
  client.query(`SELECT p.id,p.no,p.updated_at,p.branch_id,p.supplier_invoice_no ref,'authoritative purchase record' missing,'purchase_documents_core' entity_store,p.id entity_id,'clear_orphan_projection' repair_action FROM purchase_documents_core p LEFT JOIN records r ON r.tenant_id=p.tenant_id AND r.store='purchases' AND r.id=p.id WHERE p.tenant_id=$1 AND ($2='' OR COALESCE(p.branch_id,'')=$2) AND r.id IS NULL ORDER BY p.updated_at DESC LIMIT 200`,args),
  client.query(`SELECT b.id,b.data->>'batchNo' no,b.data->>'branchId' branch_id,COALESCE(NULLIF(b.data->>'qtyBase','')::numeric,0) actual,COALESCE((SELECT SUM(COALESCE(NULLIF(m.data->>'qtyBase','')::numeric,0)) FROM records m WHERE m.tenant_id=b.tenant_id AND m.store='stockMoves' AND m.data->>'batchId'=b.id),0) expected,'Batch quantity vs Stock Ledger' missing FROM records b WHERE b.tenant_id=$1 AND b.store='batches' AND ($2='' OR COALESCE(b.data->>'branchId','')=$2) AND EXISTS(SELECT 1 FROM records m WHERE m.tenant_id=b.tenant_id AND m.store='stockMoves' AND m.data->>'batchId'=b.id) AND abs(COALESCE(NULLIF(b.data->>'qtyBase','')::numeric,0)-COALESCE((SELECT SUM(COALESCE(NULLIF(m.data->>'qtyBase','')::numeric,0)) FROM records m WHERE m.tenant_id=b.tenant_id AND m.store='stockMoves' AND m.data->>'batchId'=b.id),0))>0.001 ORDER BY b.created_at DESC LIMIT 200`,args),
  client.query(`SELECT s.id,s.data->>'userName' user_name,s.data->>'branchId' branch_id,s.data->>'closedAt' at,COALESCE(NULLIF(s.data->>'expectedCash','')::numeric,0) actual,COALESCE(NULLIF(s.data->>'openingCash','')::numeric,0)+COALESCE((SELECT SUM(CASE WHEN c.data->>'direction'='out' THEN -COALESCE(NULLIF(c.data->>'amount','')::numeric,0) ELSE COALESCE(NULLIF(c.data->>'amount','')::numeric,0) END) FROM records c WHERE c.tenant_id=s.tenant_id AND c.store='cashMoves' AND c.data->>'shiftId'=s.id AND COALESCE(c.data->>'method','cash')='cash'),0) expected,'Shift cash totals' missing FROM records s WHERE s.tenant_id=$1 AND s.store='shifts' AND COALESCE(s.data->>'status','')='closed' AND ($2='' OR COALESCE(s.data->>'branchId','')=$2) AND abs(COALESCE(NULLIF(s.data->>'expectedCash','')::numeric,0)-(COALESCE(NULLIF(s.data->>'openingCash','')::numeric,0)+COALESCE((SELECT SUM(CASE WHEN c.data->>'direction'='out' THEN -COALESCE(NULLIF(c.data->>'amount','')::numeric,0) ELSE COALESCE(NULLIF(c.data->>'amount','')::numeric,0) END) FROM records c WHERE c.tenant_id=s.tenant_id AND c.store='cashMoves' AND c.data->>'shiftId'=s.id AND COALESCE(c.data->>'method','cash')='cash'),0)))>0.01 ORDER BY s.created_at DESC LIMIT 200`,args),
  client.query(`SELECT r.id,COALESCE(r.data->>'saleNo',r.data->>'saleId') no,r.data->>'at' at,r.data->>'branchId' branch_id,'Return financial bundle' missing FROM records r WHERE r.tenant_id=$1 AND r.store='returns' AND r.data->>'type'='sale_return' AND ($2='' OR COALESCE(r.data->>'branchId','')=$2) AND (NOT EXISTS(SELECT 1 FROM records j WHERE j.tenant_id=r.tenant_id AND j.store='journal' AND j.data->>'type'='sale_return' AND (j.data->>'ref'=r.id OR j.data->>'ref' LIKE 'R-'||(r.data->>'saleNo')||'%')) OR NOT EXISTS(SELECT 1 FROM audit_logs a WHERE a.tenant_id=r.tenant_id AND (a.ref=r.id OR a.detail LIKE '%'||(r.data->>'saleNo')||'%'))) ORDER BY r.created_at DESC LIMIT 200`,args),
  client.query(`WITH a AS (SELECT count(*)::numeric count,COALESCE(SUM(COALESCE(NULLIF(data->>'total','')::numeric,0)-COALESCE(NULLIF(data->>'returnedAmount','')::numeric,0)),0) total FROM records WHERE tenant_id=$1 AND store='sales' AND COALESCE(data->>'integrityStatus','')<>'quarantine' AND ($2='' OR COALESCE(data->>'branchId','')=$2)), b AS (SELECT count(*)::numeric count,COALESCE(SUM(d.total-COALESCE(d.returned_amount,0)),0) total FROM sale_documents_core d JOIN records r ON r.tenant_id=d.tenant_id AND r.store='sales' AND r.id=d.id WHERE d.tenant_id=$1 AND COALESCE(r.data->>'integrityStatus','')<>'quarantine' AND ($2='' OR COALESCE(d.branch_id,'')=$2)) SELECT 'dashboard-sales' id,'Dashboard/Reports aggregate' no,a.count expected,b.count actual,a.total expected_total,b.total actual_total,'Dashboard/Reports source mismatch' missing FROM a,b WHERE a.count<>b.count OR abs(a.total-b.total)>0.01`,args)
 ]);
 const legacy=await Promise.all([
  client.query(`SELECT m.id,m.data->>'ref' ref,m.data->>'productId' product_id,m.data->>'branchId' branch_id FROM records m WHERE m.tenant_id=$1 AND m.store='stockMoves' AND m.data->>'type'='purchase' AND ($2='' OR COALESCE(m.data->>'branchId','')=$2) AND NOT EXISTS(SELECT 1 FROM records p WHERE p.tenant_id=m.tenant_id AND p.store='purchases' AND p.data->>'no'=m.data->>'ref') ORDER BY m.created_at DESC LIMIT 100`,args),
  client.query(`SELECT o.id,o.data->>'no' no,o.data->>'status' status,o.data->>'branchId' branch_id FROM records o WHERE o.tenant_id=$1 AND o.store='purchaseOrders' AND ($2='' OR COALESCE(o.data->>'branchId','')=$2) AND COALESCE(o.data->>'status','') IN('received','partial') AND NOT EXISTS(SELECT 1 FROM records p WHERE p.tenant_id=o.tenant_id AND p.store='purchases' AND p.data->>'purchaseOrderId'=o.id) ORDER BY o.created_at DESC LIMIT 100`,args),
  client.query(`SELECT COALESCE(data->>'userId','') user_id,COALESCE(data->>'userName','') user_name,COALESCE(data->>'branchId','') branch_id,COALESCE(data->>'cashboxId','cash_main') cashbox_id,count(*)::int count,array_agg(id ORDER BY created_at) ids FROM records WHERE tenant_id=$1 AND store='shifts' AND COALESCE(data->>'status','')='open' AND ($2='' OR COALESCE(data->>'branchId','')=$2) GROUP BY 1,2,3,4 HAVING count(*)>1`,args),
  client.query(`SELECT lower(btrim(COALESCE(data->>'userName',''))) user_name,COALESCE(data->>'branchId','') branch_id,COALESCE(data->>'cashboxId','cash_main') cashbox_id,count(*)::int count,array_agg(id ORDER BY created_at) ids FROM records WHERE tenant_id=$1 AND store='shifts' AND COALESCE(data->>'status','')='open' AND ($2='' OR COALESCE(data->>'branchId','')=$2) AND btrim(COALESCE(data->>'userName',''))<>'' GROUP BY 1,2,3 HAVING count(*)>1`,args),
  client.query(`SELECT lower(btrim(COALESCE(data->>'name',''))) name,lower(btrim(COALESCE(data->>'phone',''))) phone,lower(btrim(COALESCE(data->>'taxNumber',''))) tax_number,count(*)::int count,array_agg(id ORDER BY created_at) ids FROM records WHERE tenant_id=$1 AND store='suppliers' AND btrim(COALESCE(data->>'name',''))<>'' GROUP BY 1,2,3 HAVING count(*)>1 ORDER BY count(*) DESC LIMIT 100`,[tid])
 ]);
 add('SALE_WITHOUT_STOCK' ,'Critical',qs[0].rows,{missing:'Stock Movement',action:'اعزل الفاتورة وراجع المخزون؛ لا تُنشئ حركة مخزون دون دليل',store:'sales'});
 add('SALE_CASH_MISMATCH','Critical',qs[1].rows,{action:'اعزل الفاتورة وراجع التحصيل والوردية؛ ممنوع اختراع حركة نقدية',store:'sales'});
 add('SALE_WITHOUT_GL','Critical',qs[2].rows,{action:'اعزل الفاتورة وراجع الترحيل المحاسبي قبل الإصلاح',store:'sales'});
 add('SALE_WITHOUT_AUDIT','High',qs[3].rows,{action:'راجع أصل المستند وسجل أثر المراجعة؛ لا تعيد كتابة التاريخ',store:'sales'});
 add('SALE_MISSING_PROJECTION','High',qs[4].rows,{action:'إعادة بناء الـprojection مسموحة فقط من المستند الأصلي بعد التحقق',store:'sales'});
 add('ORPHAN_SALE_PROJECTION','Critical',qs[5].rows,{action:'احذف الـprojection اليتيم فقط إذا لا توجد أي آثار مالية مرتبطة',repairAction:'clear_orphan_projection'});
 add('PURCHASE_WITHOUT_STOCK','Critical',qs[6].rows,{action:'اعزل فاتورة الشراء وراجع الاستلام والمخزون',store:'purchases'});
 add('PURCHASE_CASH_MISMATCH','Critical',qs[7].rows,{action:'اعزل فاتورة الشراء وراجع السداد والوردية',store:'purchases'});
 add('PURCHASE_WITHOUT_GL','Critical',qs[8].rows,{action:'اعزل فاتورة الشراء وراجع القيود قبل أي إصلاح',store:'purchases'});
 add('ORPHAN_SUPPLIER_INVOICE','High',qs[9].rows,{action:'إزالة الحجز/الـprojection اليتيم آمنة فقط مع غياب Purchase أصلية',repairAction:'clear_orphan_projection'});
 add('STOCK_LEDGER_MISMATCH','Critical',qs[10].rows,{action:'Quarantine للتشغيلة ومراجعة الـledger؛ لا تعدل الكمية تلقائيًا',store:'batches'});
 add('SHIFT_TOTAL_MISMATCH','High',qs[11].rows,{action:'راجع حركات الوردية ثم نفذ تسوية بصلاحية المدير إن ثبت الرصيد',store:'shifts'});
 add('RETURN_INCOMPLETE','Critical',qs[12].rows,{action:'اعزل المرتجع والمستند الأصلي؛ لا تكمل Cash/Stock/GL بلا دليل',store:'returns'});
 add('DASHBOARD_REPORT_MISMATCH','High',qs[13].rows,{action:'راجع الـprojection ومصادر التقارير قبل الاعتماد على مؤشرات الإدارة',repairAction:'review'});
 add('STOCK_WITHOUT_PURCHASE','Critical',legacy[0].rows,{action:'راجع حركة المخزون ومصدرها قبل أي تعديل'});
 add('PURCHASE_ORDER_WITHOUT_PURCHASE','High',legacy[1].rows,{action:'راجع حالة أمر الشراء والاستلام قبل تغيير الحالة',store:'purchaseOrders'});
 add('MULTIPLE_OPEN_SHIFTS','High',legacy[2].rows,{action:'راجع وأغلق/سوِّ الوردية القديمة بصلاحية مناسبة؛ لا تغلق تلقائيًا',store:'shifts'});
 add('AMBIGUOUS_OPEN_SHIFT_NAMES','Medium',legacy[3].rows,{action:'راجع ملكية الورديات المتشابهة حسب User ID قبل التشغيل'});
 add('DUPLICATE_SUPPLIERS','Medium',legacy[4].rows,{action:'راجع الموردين المكررين والحركات المرتبطة قبل الدمج'});
 const severityCounts={Critical:0,High:0,Medium:0};for(const i of issues)severityCounts[i.severity]=(severityCounts[i.severity]||0)+1;
 const byType=t=>issues.filter(x=>x.type===t).map(x=>x.details);const groups={purchaseWithoutStock:byType('PURCHASE_WITHOUT_STOCK'),stockWithoutPurchase:legacy[0].rows,paidPurchaseWithoutCash:byType('PURCHASE_CASH_MISMATCH'),purchaseOrderWithoutPurchase:legacy[1].rows,multipleOpenShifts:legacy[2].rows,ambiguousOpenShiftNames:legacy[3].rows,orphanPurchaseProjection:byType('ORPHAN_SUPPLIER_INVOICE'),duplicateSuppliers:legacy[4].rows};return{ok:issues.length===0,total:issues.length,severityCounts,issues,groups,actions:{purchaseWithoutStock:'راجع الفاتورة وحركات المخزون قبل أي تعديل',stockWithoutPurchase:'راجع مصدر حركة المخزون',paidPurchaseWithoutCash:'راجع الوردية وحركة الخزينة',purchaseOrderWithoutPurchase:'راجع حالة أمر الشراء والاستلام',multipleOpenShifts:'استخدم تسوية وإغلاق للوردية القديمة بعد المراجعة',ambiguousOpenShiftNames:'راجع ملكية الورديات المتشابهة قبل التشغيل',orphanPurchaseProjection:'استخدم التنظيف الآمن فقط إذا ثبت غياب المستند والآثار المالية',duplicateSuppliers:'راجع السجل المكرر والحركات المرتبطة قبل الدمج'},checkedAt:nowIso()};
}

 return {buildFinancialReconciliation};
};

export {};
