import type{DbExecutor,DbTx}from'../../../core/db/types.js';import type{InsuranceClaim,InsuranceContract,InsurancePlan,InsuranceProvider}from'../contracts/insurance-contract.js';
export class PostgresInsuranceRepository implements InsuranceContract{constructor(private readonly db:DbExecutor){}private ex(tx?:DbTx){return tx??this.db;}
async listProviders(t:string){return(await this.db.query<InsuranceProvider>(`SELECT id,tenant_id as "tenantId",name,code,phone,active,created_at::text as "createdAt" FROM ins_providers WHERE tenant_id=$1 ORDER BY active DESC,name`,[t])).rows;}
async saveProvider(i:InsuranceProvider,tx?:DbTx){return(await this.ex(tx).query<InsuranceProvider>(`INSERT INTO ins_providers(id,tenant_id,name,code,phone,active) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,tenant_id as "tenantId",name,code,phone,active,created_at::text as "createdAt"`,[i.id,i.tenantId,i.name,i.code,i.phone,i.active])).rows[0]!;}
async listPlans(t:string,p?:string){return(await this.db.query<InsurancePlan>(`SELECT id,tenant_id as "tenantId",provider_id as "providerId",name,coverage_percent::float as "coveragePercent",copay_percent::float as "copayPercent",annual_limit::float as "annualLimit",active FROM ins_plans WHERE tenant_id=$1 AND ($2::text IS NULL OR provider_id=$2) ORDER BY active DESC,name`,[t,p??null])).rows;}
async savePlan(i:InsurancePlan,tx?:DbTx){return(await this.ex(tx).query<InsurancePlan>(`INSERT INTO ins_plans(id,tenant_id,provider_id,name,coverage_percent,copay_percent,annual_limit,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,tenant_id as "tenantId",provider_id as "providerId",name,coverage_percent::float as "coveragePercent",copay_percent::float as "copayPercent",annual_limit::float as "annualLimit",active`,[i.id,i.tenantId,i.providerId,i.name,i.coveragePercent,i.copayPercent,i.annualLimit,i.active])).rows[0]!;}
async listClaims(t:string,limit=100){return(await this.db.query<InsuranceClaim>(`SELECT id,tenant_id as "tenantId",sale_id as "saleId",customer_id as "customerId",provider_id as "providerId",plan_id as "planId",policy_number as "policyNumber",patient_name as "patientName",gross_amount::float as "grossAmount",covered_amount::float as "coveredAmount",patient_amount::float as "patientAmount",status,reference_no as "referenceNo",note,created_at::text as "createdAt",updated_at::text as "updatedAt" FROM ins_claims WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT $2`,[t,Math.min(500,limit)])).rows;}
async getClaim(t:string,id:string,tx?:DbTx){return(await this.ex(tx).query<InsuranceClaim>(`SELECT id,tenant_id as "tenantId",sale_id as "saleId",customer_id as "customerId",provider_id as "providerId",plan_id as "planId",policy_number as "policyNumber",patient_name as "patientName",gross_amount::float as "grossAmount",covered_amount::float as "coveredAmount",patient_amount::float as "patientAmount",status,reference_no as "referenceNo",note,created_at::text as "createdAt",updated_at::text as "updatedAt" FROM ins_claims WHERE tenant_id=$1 AND id=$2`,[t,id])).rows[0]??null;}
async findBySale(t:string,saleId:string,tx?:DbTx){return(await this.ex(tx).query<InsuranceClaim>(`SELECT id,tenant_id as "tenantId",sale_id as "saleId",customer_id as "customerId",provider_id as "providerId",plan_id as "planId",policy_number as "policyNumber",patient_name as "patientName",gross_amount::float as "grossAmount",covered_amount::float as "coveredAmount",patient_amount::float as "patientAmount",status,reference_no as "referenceNo",note,created_at::text as "createdAt",updated_at::text as "updatedAt" FROM ins_claims WHERE tenant_id=$1 AND sale_id=$2`,[t,saleId])).rows[0]??null;}
async saveClaim(i:InsuranceClaim,tx?:DbTx){return(await this.ex(tx).query<InsuranceClaim>(`INSERT INTO ins_claims(id,tenant_id,sale_id,customer_id,provider_id,plan_id,policy_number,patient_name,gross_amount,covered_amount,patient_amount,status,reference_no,note) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING id,tenant_id as "tenantId",sale_id as "saleId",customer_id as "customerId",provider_id as "providerId",plan_id as "planId",policy_number as "policyNumber",patient_name as "patientName",gross_amount::float as "grossAmount",covered_amount::float as "coveredAmount",patient_amount::float as "patientAmount",status,reference_no as "referenceNo",note,created_at::text as "createdAt",updated_at::text as "updatedAt"`,[i.id,i.tenantId,i.saleId,i.customerId,i.providerId,i.planId,i.policyNumber,i.patientName,i.grossAmount,i.coveredAmount,i.patientAmount,i.status,i.referenceNo,i.note])).rows[0]!;}
async updateClaimStatus(t:string,id:string,status:InsuranceClaim['status'],referenceNo:string|null,note:string|null,tx?:DbTx){return(await this.ex(tx).query<InsuranceClaim>(`UPDATE ins_claims SET status=$3,reference_no=COALESCE($4,reference_no),note=COALESCE($5,note),updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING id,tenant_id as "tenantId",sale_id as "saleId",customer_id as "customerId",provider_id as "providerId",plan_id as "planId",policy_number as "policyNumber",patient_name as "patientName",gross_amount::float as "grossAmount",covered_amount::float as "coveredAmount",patient_amount::float as "patientAmount",status,reference_no as "referenceNo",note,created_at::text as "createdAt",updated_at::text as "updatedAt"`,[t,id,status,referenceNo,note])).rows[0]!;}}
