import type { PurchasesServiceDependencies } from '../contracts/dependencies';
'use strict';
module.exports=function create_purchases_service(ctx:PurchasesServiceDependencies){
 const {
  Finance,
  accountCode
 }=ctx;
 const serverId=(...args)=>ctx.serverId(...args);
 const nextDocumentNumber=(...args)=>ctx.nextDocumentNumber(...args);
 const sanitizeRecord=(...args)=>ctx.sanitizeRecord(...args);
 const consumeReceiptProvenance=(...args)=>ctx.consumeReceiptProvenance(...args);
 const nowIso=(...args)=>ctx.nowIso(...args);


async function preparePurchaseCommercial(c:any,tenantId:any,user:any,operations:any){
 const purOp=operations.filter(o=>o.op==='put'&&o.store==='purchases').at(-1);if(!purOp)return;
 const purchase=sanitizeRecord(purOp.value||{}),supplierId=String(purchase.supplierId||'');
 if(!supplierId||!String(purchase.supplierInvoiceNo||'').trim())throw Object.assign(new Error('PURCHASE_SUPPLIER_INVOICE_REQUIRED'),{status:422});
 const normalizedSupplierInvoice=String(purchase.supplierInvoiceNo).trim();
 // Serialize the real supplier invoice identity; failed transactions do not reserve it because the lock and writes live inside this transaction.
 await c.query('SELECT pg_advisory_xact_lock(hashtext($1))',[`${tenantId}|supplier-invoice|${supplierId}|${normalizedSupplierInvoice.toLowerCase()}`]);
 // Core tables are projections. A projection without its authoritative purchase record must never reserve a real supplier invoice number.
 await c.query(`DELETE FROM purchase_documents_core p WHERE p.tenant_id=$1 AND p.supplier_id=$2 AND lower(btrim(coalesce(p.supplier_invoice_no,'')))=lower($3) AND NOT EXISTS(SELECT 1 FROM records r WHERE r.tenant_id=p.tenant_id AND r.store='purchases' AND r.id=p.id)`,[tenantId,supplierId,normalizedSupplierInvoice]);
 const dup=await c.query(`SELECT p.id FROM purchase_documents_core p JOIN records r ON r.tenant_id=p.tenant_id AND r.store='purchases' AND r.id=p.id WHERE p.tenant_id=$1 AND p.supplier_id=$2 AND lower(btrim(coalesce(p.supplier_invoice_no,'')))=lower($3) AND p.id<>$4 LIMIT 1`,[tenantId,supplierId,normalizedSupplierInvoice,String(purchase.id||purOp.id||'')]);
 if(dup.rowCount)throw Object.assign(new Error('DUPLICATE_SUPPLIER_INVOICE'),{status:409,details:{existingId:dup.rows[0].id}});
 purchase.no=await nextDocumentNumber(c,tenantId,purchase.branchId,'purchase');
 for(const op of operations){const v=op.value||{};if(op.store==='stockMoves'&&String(v.type||'')==='purchase')v.ref=purchase.no;if(op.store==='cashMoves'&&String(v.type||'')==='supplier_payment')v.ref=purchase.no;if(op.store==='journal'&&String(v.type||'')==='purchase')v.ref=purchase.no;if(op.store==='journal'&&String(v.type||'')==='supplier_payment')v.ref=`${purchase.no}-PAY`;if(op.store==='audit'&&String(v.action||'').includes('استلام فاتورة مشتريات')){v.ref=purchase.id||purOp.id;v.detail=String(v.detail||'').replace(/P-\d{4}|PENDING-[^ •]+/g,purchase.no)}}
 const supplierRow=(await c.query(`SELECT data,revision FROM records WHERE tenant_id=$1 AND store='suppliers' AND id=$2 FOR UPDATE`,[tenantId,supplierId])).rows[0];
 if(!supplierRow)throw Object.assign(new Error('SUPPLIER_NOT_FOUND'),{status:404});
 const settings=(await c.query(`SELECT data FROM records WHERE tenant_id=$1 AND store='settings' ORDER BY created_at LIMIT 1`,[tenantId])).rows[0]?.data||{};
 const taxRegistered=settings.taxRegistered!==false,pricesIncludeTax=settings.purchasePricesIncludeTax!==false;
 const productIds=[...new Set((purchase.lines||[]).map(x=>String(x.productId||'')).filter(Boolean))];
 if(!productIds.length)throw Object.assign(new Error('PURCHASE_LINES_REQUIRED'),{status:422});
 const productRows=(await c.query(`SELECT id,data,revision FROM records WHERE tenant_id=$1 AND store='products' AND id=ANY($2::text[]) ORDER BY id FOR UPDATE`,[tenantId,productIds])).rows;
 const products=new Map<string,any>(productRows.map(r=>[String(r.id),r]));
 const existingBatchIds=[...new Set((purchase.lines||[]).map(x=>String(x.batchId||'')).filter(Boolean))].sort();
 if(existingBatchIds.length)await c.query(`SELECT id FROM records WHERE tenant_id=$1 AND store='batches' AND id=ANY($2::text[]) ORDER BY id FOR UPDATE`,[tenantId,existingBatchIds]);
 let total=0,taxTotal=0,inventoryNet=0;const cleanLines=[];
 for(const [i,raw] of (purchase.lines||[]).entries()){
   const productRow=products.get(String(raw.productId||''));if(!productRow)throw Object.assign(new Error('PRODUCT_NOT_FOUND'),{status:404,details:{line:i,productId:raw.productId}});
   const p=productRow.data||{},packs=Number(raw.packs||0),bonusPacks=Math.max(0,Number(raw.bonusPacks||0)),packCost=Math.max(0,Number(raw.packCost||0)),discount=Math.max(0,Number(raw.discount||0));
   if(!(packs>0)||!String(raw.batchNo||'').trim()||!/^\d{4}-\d{2}-\d{2}/.test(String(raw.expiry||'')))throw Object.assign(new Error('PURCHASE_LINE_INVALID'),{status:422,details:{line:i}});
   if(String(raw.expiry).slice(0,10)<new Date().toISOString().slice(0,10))throw Object.assign(new Error('PURCHASE_EXPIRED_BATCH'),{status:422,details:{line:i,batchNo:raw.batchNo}});
   const packSize=Math.max(1,Number(p.packToStrip||1)*Number(p.stripToUnit||1)),rate=taxRegistered?Math.max(0,Math.min(100,Number(raw.taxRate??p.taxRate??0))):0;
   const afterDiscount=Math.max(0,packs*packCost-Math.min(discount,packs*packCost));
   const taxAmount=Finance.money(rate>0?(pricesIncludeTax?afterDiscount*rate/(100+rate):afterDiscount*rate/100):0);
   const netAmount=Finance.money(pricesIncludeTax?afterDiscount-taxAmount:afterDiscount),lineTotal=Finance.money(pricesIncludeTax?afterDiscount:afterDiscount+taxAmount),qtyBase=Finance.money((packs+bonusPacks)*packSize),costPerBase=qtyBase?netAmount/qtyBase:0;
   if(!(qtyBase>0)||costPerBase<0)throw Object.assign(new Error('PURCHASE_COST_INVALID'),{status:422,details:{line:i}});
   const batchId=String(raw.batchId||'');if(!batchId)throw Object.assign(new Error('PURCHASE_BATCH_REQUIRED'),{status:422,details:{line:i}});
   const batchOp=operations.find(o=>o.op==='put'&&o.store==='batches'&&String(o.id)===batchId);if(!batchOp)throw Object.assign(new Error('BATCH_WRITE_REQUIRED'),{status:409,details:{line:i,batchId}});
   const current=(await c.query(`SELECT data,revision FROM records WHERE tenant_id=$1 AND store='batches' AND id=$2 FOR UPDATE`,[tenantId,batchId])).rows[0]||null;
   if(current){const b=current.data||{};if(String(b.productId||'')!==String(raw.productId))throw Object.assign(new Error('BATCH_PRODUCT_MISMATCH'),{status:409});if(String(b.batchNo||'').toLowerCase()!==String(raw.batchNo).trim().toLowerCase()||String(b.expiry||'').slice(0,10)!==String(raw.expiry).slice(0,10))throw Object.assign(new Error('BATCH_IDENTITY_MISMATCH'),{status:409});if(purchase.branchId&&b.branchId&&String(b.branchId)!==String(purchase.branchId))throw Object.assign(new Error('BATCH_BRANCH_MISMATCH'),{status:409});const oldQty=Number(b.qtyBase||0),expected=Finance.money(oldQty+qtyBase),weighted=expected>0?(oldQty*Number(b.costPerBase||0)+netAmount)/expected:costPerBase;batchOp.value={...b,_serverRevision:batchOp.value?._serverRevision,id:batchId,productId:raw.productId,batchNo:String(raw.batchNo).trim(),expiry:String(raw.expiry).slice(0,10),qtyBase:expected,costPerBase:weighted,status:b.status||'available',branchId:purchase.branchId||b.branchId||null,sourceBatchId:b.sourceBatchId||null};}
   else batchOp.value={id:batchId,productId:raw.productId,batchNo:String(raw.batchNo).trim(),expiry:String(raw.expiry).slice(0,10),qtyBase,costPerBase,supplierId,branchId:purchase.branchId||null,status:'available',receivedAt:purchase.at||nowIso()};
   const productOp=operations.find(o=>o.op==='put'&&o.store==='products'&&String(o.id)===String(raw.productId));const lastPackCost=Finance.money(netAmount/Math.max(packs,0.000001));
   if(productOp)productOp.value={...p,_serverRevision:productOp.value?._serverRevision,id:String(raw.productId),buyPrice:lastPackCost,lastPurchasePrice:lastPackCost,averageCost:Finance.money(costPerBase*packSize)};
   cleanLines.push({...raw,productName:p.name||raw.productName,batchId,batchNo:String(raw.batchNo).trim(),expiry:String(raw.expiry).slice(0,10),packs,bonusPacks,packCost,discount:Math.min(discount,packs*packCost),taxRate:rate,taxAmount,netAmount,total:lineTotal,qtyBase,costPerBase,packSize});
   total=Finance.money(total+lineTotal);taxTotal=Finance.money(taxTotal+taxAmount);inventoryNet=Finance.money(inventoryNet+netAmount);
 }
 let paid=Math.max(0,Number(purchase.paidNow||0));if(String(purchase.invoiceType||'credit')==='cash')paid=total;paid=Finance.money(Math.min(paid,total));const balance=Finance.money(total-paid);
 const oldSupplierBalance=Number(supplierRow.data?.balance||0),newSupplierBalance=Finance.money(oldSupplierBalance+balance),limit=Number(supplierRow.data?.creditLimit||0);
 if(limit>0&&newSupplierBalance>limit+0.0001)throw Object.assign(new Error('SUPPLIER_CREDIT_LIMIT_EXCEEDED'),{status:422,details:{limit,current:oldSupplierBalance,requested:balance}});
 purchase.lines=cleanLines;purchase.total=total;purchase.taxTotal=taxTotal;purchase.inventoryNet=inventoryNet;purchase.paidNow=paid;purchase.balance=balance;purchase.status=balance<=0?'paid':'posted';purchase.pricesIncludeTax=pricesIncludeTax;purchase.taxRegistered=taxRegistered;purOp.value={...purOp.value,...purchase};
 const supplierOp=operations.find(o=>o.op==='put'&&o.store==='suppliers'&&String(o.id)===supplierId);if(!supplierOp)throw Object.assign(new Error('SUPPLIER_WRITE_REQUIRED'),{status:409});supplierOp.value={...supplierRow.data,_serverRevision:supplierOp.value?._serverRevision,id:supplierId,balance:newSupplierBalance};
 const stockMoves=operations.filter(o=>o.op==='put'&&o.store==='stockMoves'&&String(o.value?.type||'')==='purchase'&&String(o.value?.ref||'')===String(purchase.no||''));
 for(const l of cleanLines){const mv=stockMoves.find(o=>String(o.value?.batchId||'')===String(l.batchId));if(mv){mv.value.qtyBase=l.qtyBase;mv.value.inventoryValue=l.netAmount;mv.value.costPerBase=l.costPerBase}}
 const journalOp=operations.find(o=>o.op==='put'&&o.store==='journal'&&String(o.value?.type||'')==='purchase');if(journalOp){journalOp.value.lines=[{accountCode:'1200',account:'المخزون',debit:inventoryNet,credit:0},...(taxTotal>0?[{accountCode:'1210',account:'ضريبة مدخلات قابلة للاسترداد',debit:taxTotal,credit:0}]:[]),{accountCode:'2000',account:'دائنون - موردون',debit:0,credit:total}];journalOp.value.debit=Finance.money(inventoryNet+taxTotal);journalOp.value.credit=total;journalOp.value.balanced=Math.abs(journalOp.value.debit-journalOp.value.credit)<0.01}
 if(paid>0){const payMethod=String(purchase.paymentMethod||'cash'),cash=operations.filter(o=>o.op==='put'&&o.store==='cashMoves'&&String(o.value?.type||'')==='supplier_payment'&&String(o.value?.ref||'')===String(purchase.no||'')&&String(o.value?.direction||'')==='out');const paidCash=Finance.money(cash.reduce((a,o)=>a+Number(o.value?.amount||0),0));if(Math.abs(paidCash-paid)>Finance.EPS)throw Object.assign(new Error('PURCHASE_PAYMENT_MOVE_MISMATCH'),{status:409,details:{expected:paid,actual:paidCash}});if(cash.some(o=>String(o.value?.method||'')!==payMethod))throw Object.assign(new Error('PURCHASE_PAYMENT_METHOD_MISMATCH'),{status:409,details:{expected:payMethod}});const pj=operations.find(o=>o.op==='put'&&o.store==='journal'&&String(o.value?.type||'')==='supplier_payment'&&String(o.value?.ref||'')===`${String(purchase.no||'')}-PAY`);if(!pj)throw Object.assign(new Error('PURCHASE_PAYMENT_JOURNAL_REQUIRED'),{status:409});const code=Finance.accountForPayment(payMethod);pj.value.lines=[{accountCode:'2000',account:'دائنون - موردون',debit:paid,credit:0},{accountCode:code,account:code==='1000'?'الخزينة':code==='1010'?'البنك':'وسائل الدفع',debit:0,credit:paid}];pj.value.debit=paid;pj.value.credit=paid;pj.value.balanced=true}
 if(purchase.purchaseOrderId){
   const poOp=operations.find(o=>o.op==='put'&&o.store==='purchaseOrders'&&String(o.id)===String(purchase.purchaseOrderId));if(!poOp)throw Object.assign(new Error('PURCHASE_ORDER_WRITE_REQUIRED'),{status:409});
   const poRow=(await c.query(`SELECT data,revision FROM records WHERE tenant_id=$1 AND store='purchaseOrders' AND id=$2 FOR UPDATE`,[tenantId,String(purchase.purchaseOrderId)])).rows[0];if(!poRow)throw Object.assign(new Error('PURCHASE_ORDER_NOT_FOUND'),{status:404});const po=poRow.data||{};
   if(String(po.supplierId||'')!==supplierId)throw Object.assign(new Error('PURCHASE_ORDER_SUPPLIER_MISMATCH'),{status:409});if(!['approved','partial'].includes(String(po.status||'')))throw Object.assign(new Error('PURCHASE_ORDER_NOT_RECEIVABLE'),{status:409,details:{status:po.status}});
   const incomingByProduct=new Map();for(const l of cleanLines)incomingByProduct.set(String(l.productId),Finance.money((incomingByProduct.get(String(l.productId))||0)+Number(l.packs||0)));
   for(const productId of incomingByProduct.keys())if(!(po.lines||[]).some(x=>String(x.productId)===productId))throw Object.assign(new Error('PURCHASE_ORDER_PRODUCT_MISMATCH'),{status:409,details:{productId}});
   const nextLines=(po.lines||[]).map(line=>{const incoming=Number(incomingByProduct.get(String(line.productId))||0),alreadyReceived=Number(line.receivedPacks||0),received=Finance.money(alreadyReceived+incoming),ordered=Number(line.packs||0),remaining=Finance.money(Math.max(0,ordered-alreadyReceived));if(received>ordered+0.0001)throw Object.assign(new Error('PURCHASE_ORDER_OVER_RECEIPT'),{status:422,details:{productId:line.productId,productName:line.productName||'',requested:incoming,remaining,ordered,alreadyReceived}});return{...line,receivedPacks:received}});
   const done=nextLines.length>0&&nextLines.every(x=>Number(x.receivedPacks||0)>=Number(x.packs||0)-0.0001);poOp.value={...po,_serverRevision:poOp.value?._serverRevision,id:String(purchase.purchaseOrderId),lines:nextLines,status:done?'received':'partial',receivedAt:done?(purchase.at||nowIso()):null,purchaseNos:[...new Set([...(po.purchaseNos||[]),String(purchase.no||'')].filter(Boolean))],purchaseNo:String(purchase.no||po.purchaseNo||'')};
 }
}

async function prepareSupplierReturnCommercial(c:any,tenantId:any,operations:any){
 const retOp=operations.filter(o=>o.op==='put'&&o.store==='supplierReturns').at(-1);if(!retOp)return;
 const ret=retOp.value||{},qty=Number(ret.qtyBase||0),batchId=String(ret.batchId||''),supplierId=String(ret.supplierId||'');
 if(!batchId||!supplierId||!(qty>0)||!String(ret.reason||'').trim())throw Object.assign(new Error('SUPPLIER_RETURN_DATA_REQUIRED'),{status:422});
 if(operations.some(o=>o.op==='put'&&o.store==='purchases'))throw Object.assign(new Error('SUPPLIER_RETURN_PURCHASE_WRITE_NOT_ALLOWED'),{status:403});
 const br=(await c.query(`SELECT data,revision FROM records WHERE tenant_id=$1 AND store='batches' AND id=$2 FOR UPDATE`,[tenantId,batchId])).rows[0];if(!br)throw Object.assign(new Error('BATCH_NOT_FOUND'),{status:404});const batch=br.data,productId=String(batch.productId||'');if(!productId)throw Object.assign(new Error('BATCH_PRODUCT_MISSING'),{status:409});const product=(await c.query(`SELECT data FROM records WHERE tenant_id=$1 AND store='products' AND id=$2`,[tenantId,productId])).rows[0]?.data||{};
 if(qty>Number(batch.qtyBase||0)+0.0001)throw Object.assign(new Error('INSUFFICIENT_STOCK'),{status:409});
 const prov=await consumeReceiptProvenance(c,tenantId,batchId,batch,qty,{supplierId,strict:false});let net=prov.net,tax=prov.tax;
 if(prov.missing>0.0001){if(String(batch.supplierId||'')!==supplierId)throw Object.assign(new Error('SUPPLIER_PROVENANCE_INSUFFICIENT'),{status:409,details:{batchId,supplierId,missing:prov.missing}});net=Finance.money(net+prov.missing*Number(batch.costPerBase||0));ret.provenanceFallback=true}
 const gross=Finance.money(net+tax),batchOp=operations.find(o=>o.op==='put'&&o.store==='batches'&&String(o.id)===batchId);if(!batchOp)throw Object.assign(new Error('BATCH_WRITE_REQUIRED'),{status:409});const expected=Finance.money(Number(batch.qtyBase||0)-qty);if(Math.abs(Number(batchOp.value?.qtyBase||0)-expected)>0.0001)throw Object.assign(new Error('BATCH_QUANTITY_MISMATCH'),{status:409});batchOp.value={...batch,_serverRevision:batchOp.value?._serverRevision,id:batchId,qtyBase:expected};
 const byPurchase=new Map();for(const a of prov.allocations){const v=Finance.money(Number(a.qtyBase||0)*(Number(a.unitCost||0)+Number(a.taxPerBase||0)));byPurchase.set(a.purchaseId,Finance.money((byPurchase.get(a.purchaseId)||0)+v))}
 let applied=0;for(const [purchaseId,credit] of byPurchase){const row=(await c.query(`SELECT data,revision FROM records WHERE tenant_id=$1 AND store='purchases' AND id=$2 FOR UPDATE`,[tenantId,String(purchaseId)])).rows[0];if(!row)continue;const doc=row.data,open=Finance.money(doc.balance),take=Math.min(open,credit);if(take<=0)continue;doc.balance=Finance.money(open-take);doc.supplierCreditApplied=Finance.money(Number(doc.supplierCreditApplied||0)+take);operations.push({op:'put',store:'purchases',id:String(purchaseId),value:doc,expectedRevision:Number(row.revision)});applied=Finance.money(applied+take);await c.query(`INSERT INTO payment_allocations(tenant_id,payment_kind,payment_id,counterparty_id,document_store,document_id,amount) VALUES($1,'refund',$2,$3,'purchases',$4,$5) ON CONFLICT DO NOTHING`,[tenantId,String(ret.id||serverId('sret')),supplierId,String(purchaseId),take])}
 const supplierRow=(await c.query(`SELECT data,revision FROM records WHERE tenant_id=$1 AND store='suppliers' AND id=$2 FOR UPDATE`,[tenantId,supplierId])).rows[0];if(!supplierRow)throw Object.assign(new Error('SUPPLIER_NOT_FOUND'),{status:404});const supplier={...(supplierRow.data||{})},excess=Finance.money(Math.max(0,gross-applied));const allOpen=(await c.query(`SELECT COALESCE(SUM((data->>'balance')::numeric),0) AS total FROM records WHERE tenant_id=$1 AND store='purchases' AND data->>'supplierId'=$2 AND id<>ALL($3::text[])`,[tenantId,supplierId,[...byPurchase.keys()]])).rows[0];let recalculated=Number(allOpen?.total||0);for(const [purchaseId] of byPurchase){const pushed=operations.find(o=>o.store==='purchases'&&String(o.id)===String(purchaseId));if(pushed)recalculated+=Number(pushed.value.balance||0);else{const q=(await c.query(`SELECT data FROM records WHERE tenant_id=$1 AND store='purchases' AND id=$2`,[tenantId,String(purchaseId)])).rows[0]?.data;recalculated+=Number(q?.balance||0)}}supplier.balance=Finance.money(recalculated);supplier.creditBalance=Finance.money(Number(supplier.creditBalance||0)+excess);const supOp=operations.find(o=>o.op==='put'&&o.store==='suppliers'&&String(o.id)===supplierId);if(supOp)supOp.value={...supplier,_serverRevision:supOp.value?._serverRevision,id:supplierId};else operations.push({op:'put',store:'suppliers',id:supplierId,value:{...supplier,id:supplierId},expectedRevision:Number(supplierRow.revision)});
 Object.assign(ret,{supplierId,supplierName:supplier.name||'',productId,productName:product.name||ret.productName||'',batchId,batchNo:batch.batchNo||ret.batchNo||'',qtyBase:qty,value:gross,inventoryValue:net,taxAmount:tax,appliedToPayables:applied,supplierCredit:excess,receiptLayers:prov.allocations});retOp.value=ret;const moves=operations.filter(o=>o.op==='put'&&o.store==='stockMoves');if(!moves.length||moves.some(o=>String(o.value?.type||'')!=='supplier_return'||String(o.value?.ref||'')!==String(ret.no||ret.id||retOp.id||'')||String(o.value?.productId||'')!==productId||String(o.value?.batchId||'')!==batchId))throw Object.assign(new Error('SUPPLIER_RETURN_STOCK_MOVE_INVALID'),{status:409});
 const journals=operations.filter(o=>o.op==='put'&&o.store==='journal'&&String(o.value?.type||'')==='supplier_return');if(journals.length!==1)throw Object.assign(new Error('SUPPLIER_RETURN_JOURNAL_REQUIRED'),{status:409});const j=journals[0];j.value.ref=j.value.ref||String(ret.no||ret.id||retOp.id||'');j.value.lines=[...(applied>0?[{accountCode:'2000',account:'دائنون - موردون',debit:applied,credit:0}]:[]),...(excess>0?[{accountCode:'1250',account:'دفعات/أرصدة لدى الموردين',debit:excess,credit:0}]:[]),...(net>0?[{accountCode:'1200',account:'المخزون',debit:0,credit:net}]:[]),...(tax>0?[{accountCode:'1210',account:'ضريبة مدخلات قابلة للاسترداد',debit:0,credit:tax}]:[])];j.value.debit=Finance.money(applied+excess);j.value.credit=Finance.money(net+tax);j.value.balanced=Math.abs(j.value.debit-j.value.credit)<0.01;if(!j.value.balanced)throw Object.assign(new Error('SUPPLIER_RETURN_JOURNAL_UNBALANCED'),{status:409});
}

 return {preparePurchaseCommercial,prepareSupplierReturnCommercial};
};

export {};
