const linesJson = `COALESCE(json_agg(json_build_object('id',l.id,'productId',l.product_id,'quantity',l.quantity::float,'unitPrice',l.unit_price::float,'discount',l.discount::float,'tax',l.tax::float,'net',l.net::float,'cost',l.cost::float,'allocations',l.allocations) ORDER BY l.id) FILTER(WHERE l.id IS NOT NULL),'[]'::json) lines`;
export class PostgresSalesRepository {
    db;
    constructor(db) {
        this.db = db;
    }
    ex(tx) { return tx ?? this.db; }
    async nextNumber(tenantId, tx) { const q = await tx.query(`INSERT INTO sales_counters(tenant_id,last_no) VALUES($1,1) ON CONFLICT(tenant_id) DO UPDATE SET last_no=sales_counters.last_no+1 RETURNING last_no as next`, [tenantId]); return `S-${String(q.rows[0].next).padStart(6, '0')}`; }
    async savePosted(s, tx) {
        await tx.query(`INSERT INTO sales_invoices(id,number,tenant_id,branch_id,customer_id,user_id,payment,subtotal,discount,invoice_discount,loyalty_points_redeemed,loyalty_discount,loyalty_points_earned,tax,total,cost,profit,status,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19)`, [s.id, s.number, s.tenantId, s.branchId, s.customerId, s.userId, s.payment, s.subtotal, s.discount, s.invoiceDiscount, s.loyaltyPointsRedeemed, s.loyaltyDiscount, s.loyaltyPointsEarned, s.tax, s.total, s.cost, s.profit, s.status, s.createdAt]);
        for (const l of s.lines)
            await tx.query(`INSERT INTO sales_lines(id,sale_id,product_id,quantity,unit_price,discount,tax,net,cost,allocations) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb)`, [l.id, s.id, l.productId, l.quantity, l.unitPrice, l.discount, l.tax, l.net, l.cost, JSON.stringify(l.allocations)]);
    }
    async get(t, id, tx) { const q = await this.ex(tx).query(`SELECT i.*,${linesJson} FROM sales_invoices i LEFT JOIN sales_lines l ON l.sale_id=i.id WHERE i.tenant_id=$1 AND i.id=$2 GROUP BY i.id`, [t, id]); const r = q.rows[0]; return r ? this.map(r) : null; }
    async list(t, limit = 100) { const q = await this.db.query(`SELECT i.*,${linesJson} FROM sales_invoices i LEFT JOIN sales_lines l ON l.sale_id=i.id WHERE i.tenant_id=$1 GROUP BY i.id ORDER BY i.created_at DESC LIMIT $2`, [t, Math.min(500, Math.max(1, limit))]); return q.rows.map((r) => this.map(r)); }
    async listByCustomer(t, customerId, limit = 100) { const q = await this.db.query(`SELECT i.*,${linesJson} FROM sales_invoices i LEFT JOIN sales_lines l ON l.sale_id=i.id WHERE i.tenant_id=$1 AND i.customer_id=$2 GROUP BY i.id ORDER BY i.created_at DESC LIMIT $3`, [t, customerId, Math.min(500, Math.max(1, limit))]); return q.rows.map((r) => this.map(r)); }
    async demandSummary(t, b, days) { const safeDays = Math.min(365, Math.max(1, Math.floor(days))); const q = await this.db.query(`WITH sold AS (SELECT l.product_id,COALESCE(sum(l.quantity),0)::float qty FROM sales_lines l JOIN sales_invoices i ON i.id=l.sale_id WHERE i.tenant_id=$1 AND i.branch_id=$2 AND i.created_at>=now()-($3::text||' days')::interval GROUP BY l.product_id), ret AS (SELECT l.product_id,COALESCE(sum(l.quantity),0)::float qty FROM sales_return_lines l JOIN sales_returns r ON r.id=l.return_id WHERE r.tenant_id=$1 AND r.branch_id=$2 AND r.created_at>=now()-($3::text||' days')::interval GROUP BY l.product_id) SELECT COALESCE(s.product_id,r.product_id) as "productId",COALESCE(s.qty,0)::float as "soldQuantity",COALESCE(r.qty,0)::float as "returnedQuantity",GREATEST(0,COALESCE(s.qty,0)-COALESCE(r.qty,0))::float as "netQuantity" FROM sold s FULL OUTER JOIN ret r ON r.product_id=s.product_id`, [t, b, String(safeDays)]); return q.rows; }
    async returnedQuantities(t, saleId, tx) { const q = await this.ex(tx).query(`SELECT l.sale_line_id as "saleLineId",COALESCE(sum(l.quantity),0)::float qty FROM sales_return_lines l JOIN sales_returns r ON r.id=l.return_id WHERE r.tenant_id=$1 AND r.sale_id=$2 GROUP BY l.sale_line_id`, [t, saleId]); return Object.fromEntries(q.rows.map(x => [x.saleLineId, x.qty])); }
    async returnedAmount(t, saleId, tx) { const q = await this.ex(tx).query(`SELECT COALESCE(sum(total),0)::float amount FROM sales_returns WHERE tenant_id=$1 AND sale_id=$2`, [t, saleId]); return q.rows[0]?.amount ?? 0; }
    async saveReturn(i, tx) {
        await tx.query(`INSERT INTO sales_returns(id,tenant_id,sale_id,branch_id,user_id,total,reason) VALUES($1,$2,$3,$4,$5,$6,$7)`, [i.id, i.tenantId, i.saleId, i.branchId, i.userId, i.total, i.reason ?? null]);
        for (const l of i.lines)
            await tx.query(`INSERT INTO sales_return_lines(id,return_id,sale_line_id,product_id,quantity,amount,classification) VALUES($1,$2,$3,$4,$5,$6,$7)`, [l.id, i.id, l.saleLineId, l.productId, l.quantity, l.amount, l.classification]);
        const remaining = await tx.query(`SELECT COALESCE(sum(sl.quantity),0)-COALESCE((SELECT sum(rl.quantity) FROM sales_return_lines rl JOIN sales_returns rr ON rr.id=rl.return_id WHERE rr.tenant_id=$2 AND rr.sale_id=$1),0)::float as "leftQty" FROM sales_lines sl WHERE sl.sale_id=$1`, [i.saleId, i.tenantId]);
        const status = (remaining.rows[0]?.leftQty ?? 1) <= 1e-9 ? 'returned' : 'partially_returned';
        await tx.query(`UPDATE sales_invoices SET status=$3 WHERE tenant_id=$1 AND id=$2`, [i.tenantId, i.saleId, status]);
    }
    map(r) { return { id: r.id, number: r.number, tenantId: r.tenant_id, branchId: r.branch_id, customerId: r.customer_id, userId: r.user_id, payment: r.payment, subtotal: Number(r.subtotal), discount: Number(r.discount), invoiceDiscount: Number(r.invoice_discount ?? 0), loyaltyPointsRedeemed: Number(r.loyalty_points_redeemed ?? 0), loyaltyDiscount: Number(r.loyalty_discount ?? 0), loyaltyPointsEarned: Number(r.loyalty_points_earned ?? 0), tax: Number(r.tax), total: Number(r.total), cost: Number(r.cost), profit: Number(r.profit), status: r.status, createdAt: new Date(r.created_at).toISOString(), lines: (r.lines ?? []).map((l) => ({ ...l, quantity: Number(l.quantity), unitPrice: Number(l.unitPrice), discount: Number(l.discount), tax: Number(l.tax), net: Number(l.net), cost: Number(l.cost), allocations: Array.isArray(l.allocations) ? l.allocations : [] })) }; }
}
