import type { SalesServiceDependencies } from '../contracts/dependencies';
'use strict';
module.exports=function create_sales_service(ctx:SalesServiceDependencies){
 const {
  Finance,
  validateSaleDocument,
  validateFefoAllocation,
  saleUnitFactor,
  saleBasePrice,
  saleOfferPrice,
  contractActiveOn,
  deriveSaleBenefits,
  insuranceSettlement,
  deriveSaleReturn,
  accountCode
 }=ctx;
 const serverId=(...args)=>ctx.serverId(...args);
 const nextDocumentNumber=(...args)=>ctx.nextDocumentNumber(...args);
 const hasAction=(...args)=>ctx.hasAction(...args);
 const sanitizeRecord=(...args)=>ctx.sanitizeRecord(...args);
 const nowIso=(...args)=>ctx.nowIso(...args);
 const consumeReceiptProvenance=(...args)=>ctx.consumeReceiptProvenance(...args);
 const restoreReceiptProvenance=(...args)=>ctx.restoreReceiptProvenance(...args);
 const clinicalAlertsForProducts=(...args)=>ctx.clinicalAlertsForProducts(...args);



async function normalizeSaleCatalog(c:any,tenantId:any,user:any,sale:any){
 const pids=[...new Set((sale.lines||[]).map(x=>String(x.productId||'')).filter(Boolean))];if(!pids.length)throw Object.assign(new Error('SALE_PRODUCTS_REQUIRED'),{status:422});
 const productRows=(await c.query(`SELECT id,data FROM records WHERE tenant_id=$1 AND store='products' AND id=ANY($2::text[]) ORDER BY id FOR SHARE`,[tenantId,pids])).rows;if(productRows.length!==pids.length)throw Object.assign(new Error('PRODUCT_NOT_FOUND'),{status:404});const products=new Map<string,any>(productRows.map(r=>[String(r.id),{...r.data,id:r.id}]));
 const offers=(await c.query(`SELECT data FROM records WHERE tenant_id=$1 AND store='offers'`,[tenantId])).rows.map(r=>r.data||{}),settings=(await c.query(`SELECT data FROM records WHERE tenant_id=$1 AND store='settings' ORDER BY created_at LIMIT 1`,[tenantId])).rows[0]?.data||{},day=String(sale.at||new Date().toISOString()).slice(0,10);
 sale.pricesIncludeTax=settings.pricesIncludeTax!==false;sale.taxRegistered=settings.taxRegistered!==false;
 for(const [index,line] of (sale.lines||[]).entries()){
   const p=products.get(String(line.productId||''));if(!p)throw Object.assign(new Error('PRODUCT_NOT_FOUND'),{status:404,details:{index}});if(String(p.status||'active')==='inactive')throw Object.assign(new Error('PRODUCT_INACTIVE'),{status:409,details:{index,productId:p.id}});
   const unit=String(line.unit||'pack'),factor=saleUnitFactor(p,unit);if(!(factor>0))throw Object.assign(new Error('INVALID_SALE_UNIT'),{status:422,details:{index,unit}});if(Math.abs(Number(line.factor||0)-factor)>0.0001)throw Object.assign(new Error('SALE_UNIT_FACTOR_MISMATCH'),{status:409,details:{index,expected:factor}});
   const base=Finance.money(saleBasePrice(p,unit)),expected=saleOfferPrice(p,unit,offers,day),actual=Finance.money(line.unitPrice);if(!hasAction(user,'priceEdit')&&Math.abs(actual-expected)>Finance.EPS)throw Object.assign(new Error('PRICE_EDIT_PERMISSION_REQUIRED'),{status:403,details:{index,expected,actual}});
   line.name=p.name||line.name;line.barcode=p.barcode||line.barcode||'';line.gtin=p.gtin||line.gtin||'';line.factor=factor;line.baseUnitPrice=base;line.taxType=p.taxType||'';line.taxRate=Number(p.taxRate||0);
 }
 return settings;
}

async function prepareSaleCommercial(c:any,tenantId:any,user:any,operations:any){
 const saleOp=operations.filter(o=>o.op==='put'&&o.store==='sales').at(-1);if(!saleOp)return;
 const sale=sanitizeRecord(saleOp.value||{}),settings=await normalizeSaleCatalog(c,tenantId,user,sale);sale.no=await nextDocumentNumber(c,tenantId,sale.branchId,'sale');for(const op of operations){const v=op.value||{};if(op.store==='cashMoves'&&v.type==='sale')v.ref=sale.no;if(op.store==='journal'&&String(v.type||'').startsWith('sale'))v.ref=sale.no;if(op.store==='claims'&&String(v.saleId||'')===String(sale.id||saleOp.id))v.saleNo=sale.no;if(op.store==='loyalty'&&String(v.saleId||'')===String(sale.id||saleOp.id))v.saleNo=sale.no;if(op.store==='audit'&&String(v.action||'').includes('فاتورة بيع')){v.ref=sale.id||saleOp.id;v.detail=String(v.detail||'').replace(/S-\d{4}|PENDING-[^ —]+/g,sale.no)}}
 if(String(sale.payment||'')==='credit'&&!hasAction(user,'creditSale'))throw Object.assign(new Error('CREDIT_SALE_PERMISSION_REQUIRED'),{status:403});
 const customerOps=operations.filter(o=>o.op==='put'&&o.store==='customers'),customerId=String(sale.customerId||'');if(customerOps.some(o=>String(o.id)!==customerId)||(!customerId&&customerOps.length))throw Object.assign(new Error('SALE_CUSTOMER_WRITE_NOT_ALLOWED'),{status:403});let customerRow=null,customer=null,customerOp=null;
 if(customerId){customerRow=(await c.query(`SELECT data,revision FROM records WHERE tenant_id=$1 AND store='customers' AND id=$2 FOR UPDATE`,[tenantId,customerId])).rows[0];if(!customerRow)throw Object.assign(new Error('CUSTOMER_NOT_FOUND'),{status:404});customer=customerRow.data||{};customerOp=customerOps.find(o=>String(o.id)===customerId);if(!customerOp)throw Object.assign(new Error('CUSTOMER_WRITE_REQUIRED'),{status:409})}
 if(String(sale.payment||'')==='credit'&&!customer)throw Object.assign(new Error('CREDIT_CUSTOMER_REQUIRED'),{status:422});
 const clinicalAlerts=await clinicalAlertsForProducts(c,tenantId,(sale.lines||[]).map(x=>x.productId),customerId);sale.clinicalAlerts=clinicalAlerts.map(x=>({type:x.type,severity:x.severity,message:x.message,source:x.source||''}));if(clinicalAlerts.some(x=>String(x.severity||'').toLowerCase()==='danger')&&sale.clinicalReviewed!==true)throw Object.assign(new Error('CLINICAL_REVIEW_REQUIRED'),{status:409,details:{alerts:sale.clinicalAlerts}});
 const beforeBenefits=Finance.computeSale(sale.lines,{discount:sale.discount,pointsDiscount:0,contractDiscount:0,deliveryFee:sale.deliveryFee,pricesIncludeTax:sale.pricesIncludeTax,taxRegistered:sale.taxRegistered}),contractOps=operations.filter(o=>o.op==='put'&&o.store==='claims');let contract=null;if(String(sale.payment||'')==='insurance'){if(!sale.contractId)throw Object.assign(new Error('INSURANCE_CUSTOMER_CONTRACT_REQUIRED'),{status:422});contract=(await c.query(`SELECT data FROM records WHERE tenant_id=$1 AND store='contracts' AND id=$2 FOR SHARE`,[tenantId,String(sale.contractId)])).rows[0]?.data;if(!contract||!contractActiveOn(contract,String(sale.at||new Date().toISOString()).slice(0,10)))throw Object.assign(new Error('CONTRACT_NOT_ACTIVE'),{status:409});sale.contractName=contract.name||sale.contractName||''}else{if(Number(sale.contractDiscount||0)>Finance.EPS||sale.contractId)throw Object.assign(new Error('CONTRACT_DISCOUNT_NOT_ALLOWED'),{status:422});if(contractOps.length)throw Object.assign(new Error('CLAIM_NOT_ALLOWED'),{status:403})}const benefits=deriveSaleBenefits({subtotal:beforeBenefits.subtotal,discount:beforeBenefits.discount,requestedPointsDiscount:sale.pointsDiscount,customerPoints:customer?.points||0,redeemValue:settings.loyaltyRedeemValue,payment:String(sale.payment||''),contract,hasCustomer:!!customer});sale.pointsDiscount=benefits.pointsDiscount;sale.contractDiscount=benefits.contractDiscount;
 const computed=Finance.computeSale(sale.lines,{discount:sale.discount,pointsDiscount:sale.pointsDiscount,contractDiscount:sale.contractDiscount,deliveryFee:sale.deliveryFee,pricesIncludeTax:sale.pricesIncludeTax,taxRegistered:sale.taxRegistered});sale.lines=computed.lines;sale.subtotal=computed.subtotal;sale.discount=computed.discount;sale.pointsDiscount=computed.pointsDiscount;sale.contractDiscount=computed.contractDiscount;sale.deliveryFee=computed.deliveryFee;sale.taxTotal=computed.taxTotal;sale.salesNet=computed.salesNet;sale.total=computed.total;
 if(String(sale.payment||'')==='insurance'){const {claimAmount,customerPay}=insuranceSettlement(sale.total,contract);sale.claimAmount=claimAmount;sale.customerPay=customerPay;const claims=contractOps.filter(o=>String(o.value?.saleId||'')===String(sale.id||saleOp.id));if(claims.length!==1)throw Object.assign(new Error('INSURANCE_CLAIM_REQUIRED'),{status:409});claims[0].value={...claims[0].value,contractId:sale.contractId,contractName:sale.contractName,customerId,customerName:customer.name||sale.customerName||'',saleId:sale.id||saleOp.id,saleNo:sale.no,amount:claimAmount,status:'pending'};const paid=operations.filter(o=>o.op==='put'&&o.store==='cashMoves'&&o.value?.type==='sale'&&String(o.value?.ref||'')===String(sale.no||'')&&o.value?.direction==='in').reduce((a,o)=>a+Number(o.value?.amount||0),0);if(Math.abs(paid-customerPay)>Finance.EPS)throw Object.assign(new Error('INSURANCE_CASH_MOVE_MISMATCH'),{status:409,details:{expected:customerPay,actual:paid}})}
 validateSaleDocument(sale,Number(user.maxDiscountPercent||0));
 if(customer){const usedPoints=benefits.usedPoints,earnEvery=Math.max(0.000001,Number(settings.loyaltyEarnEvery)||10),earned=Math.floor(sale.total/earnEvery),newBalance=String(sale.payment||'')==='credit'?Finance.money(Number(customer.balance||0)+sale.total):Finance.money(Number(customer.balance||0)),limit=Number(customer.creditLimit||0);if(String(sale.payment||'')==='credit'&&limit>0&&newBalance>limit+0.0001)throw Object.assign(new Error('CUSTOMER_CREDIT_LIMIT_EXCEEDED'),{status:422,details:{limit,current:Number(customer.balance||0),requested:sale.total}});sale.loyaltyUsedPoints=usedPoints;sale.loyaltyEarnedPoints=earned;sale.loyaltyEarnEvery=earnEvery;sale.loyaltyRedeemValue=Math.max(0.000001,Number(settings.loyaltyRedeemValue)||.1);sale.loyaltyReversedEarnedPoints=0;sale.loyaltyRestoredUsedPoints=0;customerOp.value={...customer,id:customerId,balance:newBalance,points:Math.max(0,Number(customer.points||0)-usedPoints)+earned};const loy=operations.filter(o=>o.op==='put'&&o.store==='loyalty');if(loy.length>1)throw Object.assign(new Error('SALE_LOYALTY_WRITE_INVALID'),{status:409});if((usedPoints>0||earned>0)&&!loy.length){const loyaltyId=serverId('loy');operations.push({op:'put',store:'loyalty',id:loyaltyId,value:{id:loyaltyId,customerId,customerName:customer.name||sale.customerName||'',saleId:sale.id||saleOp.id,saleNo:sale.no,points:earned-usedPoints,earnedPoints:earned,usedPoints:-usedPoints,note:'حركة نقاط تلقائية من فاتورة بيع',type:'sale',at:sale.at||nowIso(),branchId:sale.branchId||null,userId:user?.id||null,userName:user?.name||''}})};}

 const productIds=[...new Set((sale.lines||[]).map(x=>String(x.productId||'')).filter(Boolean))];let cost=0;
 if(productIds.length){
   const rows=(await c.query(`SELECT r.id,r.data,r.revision,b.product_id,b.expiry,b.qty_base FROM records r JOIN batches_core b ON b.tenant_id=r.tenant_id AND b.id=r.id WHERE r.tenant_id=$1 AND r.store='batches' AND b.product_id=ANY($2::text[]) AND b.qty_base>0 AND b.status='available' AND (b.expiry IS NULL OR b.expiry>=CURRENT_DATE) AND ($3='' OR b.branch_id IS NULL OR b.branch_id=$3) ORDER BY b.product_id,b.expiry NULLS LAST,r.id FOR UPDATE OF r`,[tenantId,productIds,String(sale.branchId||'')])).rows;
   const remaining=new Map<string,number>(rows.map(r=>[String(r.id),Number(r.qty_base||0)])),usage=new Map<string,number>(),map=new Map<string,any>(rows.map(r=>[String(r.id),r]));
   for(const line of sale.lines||[]){let need=Number(line.qty||0)*Number(line.factor||1);line.allocations=[];for(const r of rows){if(need<=0.0001)break;if(String(r.product_id)!==String(line.productId||''))continue;const available=remaining.get(String(r.id))||0;if(available<=0)continue;const take=Math.min(need,available),b=r.data||{};line.allocations.push({batchId:r.id,batchNo:b.batchNo||'',qtyBase:take,costPerBase:Number(b.costPerBase||0)});remaining.set(String(r.id),Finance.money(available-take));usage.set(String(r.id),Finance.money((usage.get(String(r.id))||0)+take));need=Finance.money(need-take);cost+=take*Number(b.costPerBase||0)}if(need>0.0001)throw Object.assign(new Error('INSUFFICIENT_STOCK'),{status:409,details:{productId:line.productId,missing:need}})}
   validateFefoAllocation(sale.lines,rows.map(r=>({id:r.id,productId:r.product_id,expiry:r.expiry,qtyBase:r.qty_base})),usage);
   for(let i=operations.length-1;i>=0;i--){const op=operations[i],v=op.value||{};if(op.store==='batches'||(op.store==='stockMoves'&&String(v.type||'')==='sale'))operations.splice(i,1)}
   for(const [bid,qty] of usage){const r=map.get(bid),b={...(r.data||{}),id:bid,qtyBase:Finance.money(Number(r.qty_base||0)-qty)};if(Number(b.qtyBase)<-0.0001)throw Object.assign(new Error('INSUFFICIENT_STOCK'),{status:409});operations.push({op:'put',store:'batches',id:bid,value:b,expectedRevision:Number(r.revision||0)});const moveId=serverId('smv');operations.push({op:'put',store:'stockMoves',id:moveId,value:{id:moveId,at:sale.at||nowIso(),productId:String(r.product_id),batchId:bid,qtyBase:-qty,type:'sale',ref:sale.no,note:`بيع ${sale.lines.find(l=>String(l.productId)===String(r.product_id))?.name||''}`,branchId:sale.branchId||b.branchId||null}})}
   for(const line of sale.lines||[])for(const a of line.allocations||[]){const r=map.get(String(a.batchId)),b=r?.data||{};const prov=await consumeReceiptProvenance(c,tenantId,String(a.batchId),b,Number(a.qtyBase||0));if(prov.allocations.length)a.receiptLayers=prov.allocations}
 }
 sale.cost=Finance.money(cost);sale.grossProfit=Finance.money(Number(sale.salesNet||0)-sale.cost);saleOp.value={...saleOp.value,...sale};
 const j=operations.find(o=>o.op==='put'&&o.store==='journal'&&String(o.value?.type||'').startsWith('sale'));
 if(!j)throw Object.assign(new Error('SALE_JOURNAL_REQUIRED'),{status:409});
 const debitLines=[],payment=String(sale.payment||'');
 if(payment==='credit')debitLines.push({accountCode:'1100',account:'عملاء',debit:sale.total,credit:0});
 else if(payment==='insurance'){if(Number(sale.customerPay||0)>0)debitLines.push({accountCode:'1000',account:'الخزينة',debit:sale.customerPay,credit:0});if(Number(sale.claimAmount||0)>0)debitLines.push({accountCode:'1150',account:'مطالبات التأمين',debit:sale.claimAmount,credit:0})}
 else if(payment==='split'){
   const byMethod={};for(const m of operations.filter(o=>o.op==='put'&&o.store==='cashMoves'&&String(o.value?.type||'')==='sale'&&String(o.value?.ref||'')===String(sale.no||'')&&String(o.value?.direction||'')==='in')){const method=String(m.value?.method||'cash');byMethod[method]=Finance.money((byMethod[method]||0)+Number(m.value?.amount||0))}for(const [method,amount] of Object.entries(byMethod)){const code=Finance.accountForPayment(method);debitLines.push({accountCode:code,account:code==='1000'?'الخزينة':code==='1010'?'البنك':'وسائل التحصيل',debit:amount,credit:0})}
 } else {const code=Finance.accountForPayment(payment||'cash');debitLines.push({accountCode:code,account:code==='1000'?'الخزينة':code==='1010'?'البنك':'وسائل التحصيل',debit:sale.total,credit:0})}
 const lines=[...debitLines,{accountCode:'4000',account:'المبيعات',debit:0,credit:sale.salesNet},...(Number(sale.taxTotal||0)>0?[{accountCode:'2100',account:'ضريبة مخرجات مستحقة',debit:0,credit:sale.taxTotal}]:[]),...(Number(sale.deliveryFee||0)>0?[{accountCode:'4100',account:'إيرادات التوصيل',debit:0,credit:sale.deliveryFee}]:[]),...(sale.cost>0?[{accountCode:'5000',account:'تكلفة البضاعة المباعة',debit:sale.cost,credit:0},{accountCode:'1200',account:'المخزون',debit:0,credit:sale.cost}]:[])];
 j.value.lines=lines;j.value.debit=Finance.money(lines.reduce((a,l)=>a+Number(l.debit||0),0));j.value.credit=Finance.money(lines.reduce((a,l)=>a+Number(l.credit||0),0));j.value.balanced=Math.abs(j.value.debit-j.value.credit)<0.01;if(!j.value.balanced)throw Object.assign(new Error('SALE_JOURNAL_UNBALANCED'),{status:409,details:{debit:j.value.debit,credit:j.value.credit}});
}

async function prepareInsuranceClaimsCommercial(c:any,tenantId:any,operations:any){
 const claimOps=operations.filter(o=>o.op==='put'&&o.store==='claims');if(!claimOps.length)return;
 for(const op of claimOps){const id=String(op.id||op.value?.id||''),incoming=sanitizeRecord(op.value||{});if(!id)throw Object.assign(new Error('CLAIM_ID_REQUIRED'),{status:422});
   const row=(await c.query(`SELECT data,revision FROM records WHERE tenant_id=$1 AND store='claims' AND id=$2 FOR UPDATE`,[tenantId,id])).rows[0];
   if(!row)continue; // New claims are created only by the dedicated sale intent and validated there.
   const old=row.data||{},oldStatus=String(old.status||'pending'),newStatus=String(incoming.status||oldStatus),oldAmount=Finance.money(old.amount||0),newAmount=Finance.money(incoming.amount??oldAmount);
   if(Math.abs(newAmount-oldAmount)>Finance.EPS)throw Object.assign(new Error('CLAIM_AMOUNT_CHANGE_NOT_ALLOWED'),{status:409});
   if(['paid','cancelled'].includes(oldStatus)&&newStatus!==oldStatus)throw Object.assign(new Error('CLAIM_FINAL_STATE'),{status:409});
   if(oldStatus==='pending'&&newStatus==='paid')throw Object.assign(new Error('CLAIM_APPROVAL_REQUIRED'),{status:409});
   if(!['pending','approved','paid','cancelled'].includes(newStatus))throw Object.assign(new Error('CLAIM_STATUS_INVALID'),{status:422});
   if(newStatus==='approved'&&oldStatus==='pending')op.value={...old,...incoming,id,amount:oldAmount,status:'approved',approvedAt:incoming.approvedAt||nowIso()};
   if(newStatus==='paid'&&oldStatus==='approved'){
     const ref=String(old.saleNo||incoming.saleNo||''),cash=operations.filter(o=>o.op==='put'&&o.store==='cashMoves'&&String(o.value?.type||'')==='insurance_collection'&&String(o.value?.ref||'')===ref&&String(o.value?.direction||'')==='in');
     const received=Finance.money(cash.reduce((a,o)=>a+Number(o.value?.amount||0),0));if(Math.abs(received-oldAmount)>Finance.EPS)throw Object.assign(new Error('CLAIM_COLLECTION_MISMATCH'),{status:409,details:{expected:oldAmount,actual:received}});
     const journals=operations.filter(o=>o.op==='put'&&o.store==='journal'&&String(o.value?.type||'')==='insurance_collection');if(journals.length!==1)throw Object.assign(new Error('CLAIM_COLLECTION_JOURNAL_REQUIRED'),{status:409});
     const j=journals[0],payMethod=String(cash[0]?.value?.method||'bank'),debitCode=Finance.accountForPayment(payMethod);j.value.ref=j.value.ref||`${ref}-CLM`;j.value.lines=[{accountCode:debitCode,account:debitCode==='1000'?'الخزينة':debitCode==='1010'?'البنك':'وسائل تحصيل',debit:oldAmount,credit:0},{accountCode:'1150',account:'مطالبات التأمين',debit:0,credit:oldAmount}];j.value.debit=oldAmount;j.value.credit=oldAmount;j.value.balanced=true;
     op.value={...old,...incoming,id,amount:oldAmount,status:'paid',paidAt:incoming.paidAt||nowIso()};
   }
 }
}

async function prepareReturnCommercial(c:any,tenantId:any,user:any,operations:any){
 const retOp=operations.filter(o=>o.op==='put'&&o.store==='returns'&&o.value?.type==='sale_return').at(-1);if(!retOp)return;
 const incoming=retOp.value||{},saleRow=(await c.query(`SELECT data,revision FROM records WHERE tenant_id=$1 AND store='sales' AND id=$2 FOR UPDATE`,[tenantId,String(incoming.saleId||'')])).rows[0];if(!saleRow)throw Object.assign(new Error('SALE_NOT_FOUND'),{status:404});const old=saleRow.data||{};if(['quarantine','void'].includes(String(old.integrityStatus||'')))throw Object.assign(new Error('SALE_REQUIRES_REPAIR_WORKFLOW'),{status:409});const derived=deriveSaleReturn(old,incoming.items||[]),ret={...incoming,items:derived.items,total:derived.total,net:derived.net,tax:derived.tax,deliveryRefund:derived.deliveryRefund,inspectedBy:user?.name||incoming.inspectedBy||'',inspectedAt:nowIso()};retOp.value=ret;
 const saleOp=operations.filter(o=>o.op==='put'&&o.store==='sales'&&String(o.id)===String(incoming.saleId)).at(-1);if(!saleOp)throw Object.assign(new Error('RETURN_SALE_WRITE_REQUIRED'),{status:409});
 const used={...(old.returnedBaseByBatch||{})},usedLayers={...(old.returnedReceiptByLayer||{})},sourceCosts=new Map(),sourceQty=new Map(),sourceProduct=new Map(),items=derived.items;let returnedCost=0;const provenanceToRestore=[];
 for(const item of items){const line=old.lines[Number(item.lineIndex)];let need=Number(item.qty||0)*Number(line.factor||1);for(const a of line.allocations||[]){if(need<=0)break;const avail=Math.max(0,Number(a.qtyBase||0)-Number(used[a.batchId]||0)),take=Math.min(need,avail);if(take>0){returnedCost+=take*Number(a.costPerBase||0);sourceCosts.set(String(a.batchId),Number(a.costPerBase||0));sourceQty.set(String(a.batchId),Finance.money((sourceQty.get(String(a.batchId))||0)+take));sourceProduct.set(String(a.batchId),String(line.productId||''));used[a.batchId]=Finance.money(Number(used[a.batchId]||0)+take);let provNeed=take;for(const pr of a.receiptLayers||[]){if(provNeed<=0)break;const already=Number(usedLayers[pr.layerId]||0),pAvail=Math.max(0,Number(pr.qtyBase||0)-already),pTake=Math.min(provNeed,pAvail);if(pTake>0){provenanceToRestore.push({...pr,qtyBase:pTake});usedLayers[pr.layerId]=already+pTake;provNeed-=pTake}}need-=take}}if(need>0.0001)throw Object.assign(new Error('RETURN_BATCH_ALLOCATION_INVALID'),{status:409})}
 returnedCost=Finance.money(returnedCost);const restored=['resalable','quarantine'].includes(String(ret.disposition||''))?returnedCost:0;ret.cost=returnedCost;ret.costRestored=restored;if(provenanceToRestore.length)await restoreReceiptProvenance(c,tenantId,provenanceToRestore);ret.receiptLayers=provenanceToRestore;
 const inspections=Array.isArray(ret.inspections)?ret.inspections:[],inspectionBySource=new Map();for(const ins of inspections){if(String(ins.disposition||ret.disposition)!==String(ret.disposition))throw Object.assign(new Error('RETURN_INSPECTION_DISPOSITION_MISMATCH'),{status:409});const sid=String(ins.sourceBatchId||'');if(!sourceQty.has(sid))throw Object.assign(new Error('RETURN_INSPECTION_SOURCE_INVALID'),{status:409});if(String(ins.productId||'')!==sourceProduct.get(sid))throw Object.assign(new Error('RETURN_INSPECTION_PRODUCT_MISMATCH'),{status:409});const q=Number(ins.qtyBase||0);if(!(q>0))throw Object.assign(new Error('RETURN_INSPECTION_QTY_INVALID'),{status:422});inspectionBySource.set(sid,Finance.money((inspectionBySource.get(sid)||0)+q));ins.inspectedBy=user?.name||'';ins.inspectedAt=ret.inspectedAt;ins.disposition=ret.disposition;ins.reason=ret.reason}
 for(const [sid,qty] of sourceQty){if(Math.abs(Number(inspectionBySource.get(sid)||0)-qty)>0.0001)throw Object.assign(new Error('RETURN_INSPECTION_QTY_MISMATCH'),{status:409,details:{batchId:sid,expected:qty,actual:Number(inspectionBySource.get(sid)||0)}});const sourceRow=(await c.query(`SELECT data,revision FROM records WHERE tenant_id=$1 AND store='batches' AND id=$2 FOR UPDATE`,[tenantId,sid])).rows[0];if(!sourceRow)throw Object.assign(new Error('BATCH_NOT_FOUND'),{status:404});const source=sourceRow.data||{};if(ret.disposition==='resalable'){const op=operations.find(o=>o.op==='put'&&o.store==='batches'&&String(o.id)===sid);if(!op)throw Object.assign(new Error('BATCH_WRITE_REQUIRED'),{status:409});const expected=Finance.money(Number(source.qtyBase||0)+qty);if(Math.abs(Number(op.value?.qtyBase||0)-expected)>0.0001)throw Object.assign(new Error('BATCH_QUANTITY_MISMATCH'),{status:409,details:{batchId:sid,expected,actual:Number(op.value?.qtyBase||0)}});op.value={...source,...op.value,id:sid,productId:sourceProduct.get(sid),qtyBase:expected,costPerBase:Number(sourceCosts.get(sid)||source.costPerBase||0),status:'available'}}}
 if(ret.disposition!=='resalable'){for(const ins of inspections){const targetId=String(ins.batchId||'');if(!targetId||targetId===String(ins.sourceBatchId||''))throw Object.assign(new Error('RETURN_QUARANTINE_BATCH_REQUIRED'),{status:409});const existing=(await c.query(`SELECT 1 FROM records WHERE tenant_id=$1 AND store='batches' AND id=$2`,[tenantId,targetId])).rowCount;if(existing)throw Object.assign(new Error('RETURN_TARGET_BATCH_EXISTS'),{status:409});const op=operations.find(o=>o.op==='put'&&o.store==='batches'&&String(o.id)===targetId);if(!op)throw Object.assign(new Error('RETURN_TARGET_BATCH_WRITE_REQUIRED'),{status:409});const sourceRow=(await c.query(`SELECT data FROM records WHERE tenant_id=$1 AND store='batches' AND id=$2`,[tenantId,String(ins.sourceBatchId)])).rows[0]?.data||{},cpb=Number(sourceCosts.get(String(ins.sourceBatchId))||0);op.value={...op.value,id:targetId,productId:sourceProduct.get(String(ins.sourceBatchId)),branchId:old.branchId||op.value?.branchId||null,batchNo:sourceRow.batchNo||op.value?.batchNo||'',expiry:sourceRow.expiry||op.value?.expiry||null,qtyBase:Number(ins.qtyBase),costPerBase:ret.disposition==='quarantine'?cpb:0,originalCostPerBase:cpb,supplierId:sourceRow.supplierId||null,status:ret.disposition==='quarantine'?'quarantine':ret.disposition==='expired'?'expired':'waste',sourceBatchId:String(ins.sourceBatchId),returnId:String(ret.id||retOp.id),receivedAt:ret.inspectedAt}}
 }
 const customerOps=operations.filter(o=>o.op==='put'&&o.store==='customers'),cashOps=operations.filter(o=>o.op==='put'&&o.store==='cashMoves'),claimOps=operations.filter(o=>o.op==='put'&&o.store==='claims'),refundMethod=String(ret.refundMethod||'original'),settlementCredits=[];let expectedCash=0,customerOp=null,customer=null,customerRevision=0;
 if(customerOps.some(o=>String(o.id)!==String(old.customerId||'')))throw Object.assign(new Error('RETURN_CUSTOMER_WRITE_NOT_ALLOWED'),{status:403});if(customerOps.length>1)throw Object.assign(new Error('RETURN_CUSTOMER_WRITE_INVALID'),{status:409});
 const loyaltyTracked=!!old.customerId&&(old.loyaltyEarnedPoints!=null||old.loyaltyUsedPoints!=null);if(loyaltyTracked){const row=(await c.query(`SELECT data,revision FROM records WHERE tenant_id=$1 AND store='customers' AND id=$2 FOR UPDATE`,[tenantId,String(old.customerId)])).rows[0];if(!row)throw Object.assign(new Error('CUSTOMER_NOT_FOUND'),{status:404});customer=row.data||{};customerRevision=Number(row.revision||0);customerOp=customerOps[0];if(!customerOp){customerOp={op:'put',store:'customers',id:String(old.customerId),value:{...customer,id:String(old.customerId),_serverRevision:customerRevision}};customerOps.push(customerOp);operations.push(customerOp)}}
 if(refundMethod==='customer_credit'||(String(old.payment)==='credit'&&refundMethod==='original')){if(!old.customerId)throw Object.assign(new Error('RETURN_CUSTOMER_REQUIRED'),{status:422});if(!customer){const row=(await c.query(`SELECT data,revision FROM records WHERE tenant_id=$1 AND store='customers' AND id=$2 FOR UPDATE`,[tenantId,String(old.customerId)])).rows[0];if(!row)throw Object.assign(new Error('CUSTOMER_NOT_FOUND'),{status:404});customer=row.data||{};customerRevision=Number(row.revision||0)}customerOp=customerOps[0];if(!customerOp)throw Object.assign(new Error('RETURN_CUSTOMER_WRITE_REQUIRED'),{status:409})}
 if(refundMethod==='customer_credit'){customerOp.value={...customer,creditBalance:Finance.money(Number(customer.creditBalance||0)+derived.total)};settlementCredits.push({accountCode:'2050',account:'أرصدة دائنة للعملاء',debit:0,credit:derived.total})}
 else if(String(old.payment)==='credit'&&refundMethod==='original'){const outstanding=Math.max(0,Number(old.creditBalance||0)),arReduction=Math.min(derived.total,outstanding),excess=Finance.money(derived.total-arReduction);customerOp.value={...customer,balance:Math.max(0,Finance.money(Number(customer.balance||0)-arReduction)),creditBalance:Finance.money(Number(customer.creditBalance||0)+excess)};old.creditBalance=Finance.money(outstanding-arReduction);if(arReduction>0)settlementCredits.push({accountCode:'1100',account:'عملاء',debit:0,credit:arReduction});if(excess>0)settlementCredits.push({accountCode:'2050',account:'أرصدة دائنة للعملاء',debit:0,credit:excess})}
 else if(String(old.payment)==='insurance'&&refundMethod==='original'){const base=Math.max(0.01,Number(old.total||0)),customerPart=Finance.money(derived.total*Number(old.customerPay||0)/base),claimPart=Finance.money(derived.total-customerPart);expectedCash=customerPart;if(customerPart>0)settlementCredits.push({accountCode:'1000',account:'الخزينة',debit:0,credit:customerPart});if(claimPart>0){settlementCredits.push({accountCode:'1150',account:'مطالبات التأمين',debit:0,credit:claimPart});const claimRow=(await c.query(`SELECT id,data FROM records WHERE tenant_id=$1 AND store='claims' AND data->>'saleId'=$2 AND COALESCE(data->>'status','')<>'cancelled' ORDER BY created_at LIMIT 1 FOR UPDATE`,[tenantId,String(old.id||incoming.saleId)])).rows[0];if(claimRow){const op=claimOps.find(o=>String(o.id)===String(claimRow.id));if(!op)throw Object.assign(new Error('RETURN_CLAIM_WRITE_REQUIRED'),{status:409});op.value={...claimRow.data,amount:Math.max(0,Finance.money(Number(claimRow.data?.amount||0)-claimPart)),status:derived.fully?'cancelled':claimRow.data?.status,adjustedAt:ret.inspectedAt}}}
 }
 else{expectedCash=derived.total;if(String(old.payment)==='split'&&refundMethod==='original'){const entries=Object.entries(old.splitPayments||{}).filter(([,v])=>Number(v)>0),base=Math.max(0.01,entries.reduce((a,[,v])=>a+Number(v),0));let allocated=0;entries.forEach(([method,value],i)=>{const amount=i===entries.length-1?Finance.money(derived.total-allocated):Finance.money(derived.total*Number(value)/base);allocated=Finance.money(allocated+amount);const account=Finance.accountForPayment(method);settlementCredits.push({accountCode:account,account:account==='1000'?'الخزينة':account==='1010'?'البنك':'وسائل تحصيل',debit:0,credit:amount,method})})}else{const account=Finance.accountForPayment(refundMethod==='original'?String(old.payment||'cash'):refundMethod);settlementCredits.push({accountCode:account,account:account==='1000'?'الخزينة':account==='1010'?'البنك':'وسائل تحصيل',debit:0,credit:derived.total})}}
 if(loyaltyTracked&&customerOp){const totalBase=Math.max(0.01,Number(old.total||0)),cumulativeReturned=Math.min(totalBase,Finance.money(Number(old.returnedAmount||0)+derived.total)),earnEvery=Math.max(0.000001,Number(old.loyaltyEarnEvery)||10),originalEarned=Math.max(0,Math.trunc(Number(old.loyaltyEarnedPoints||0))),originalUsed=Math.max(0,Math.trunc(Number(old.loyaltyUsedPoints||0))),previousEarnedReversed=Math.max(0,Math.trunc(Number(old.loyaltyReversedEarnedPoints||0))),previousUsedRestored=Math.max(0,Math.trunc(Number(old.loyaltyRestoredUsedPoints||0))),retained=Math.max(0,totalBase-cumulativeReturned),targetEarned=derived.fully?0:Math.min(originalEarned,Math.floor(retained/earnEvery)),targetEarnedReversed=Math.max(0,originalEarned-targetEarned),targetUsedRestored=derived.fully?originalUsed:Math.min(originalUsed,Math.floor(originalUsed*cumulativeReturned/totalBase)),earnedDelta=Math.max(0,targetEarnedReversed-previousEarnedReversed),restoreDelta=Math.max(0,targetUsedRestored-previousUsedRestored),basePoints=Math.max(0,Number((customerOp.value?.points??customer?.points??0)));customerOp.value={...customer,...customerOp.value,id:String(old.customerId),_serverRevision:customerOp.value?._serverRevision??customerRevision,points:Math.max(0,Math.trunc(basePoints)-earnedDelta+restoreDelta)};ret.loyaltyEarnedPointsReversed=earnedDelta;ret.loyaltyUsedPointsRestored=restoreDelta;ret.loyaltyPointsDelta=restoreDelta-earnedDelta;old.loyaltyReversedEarnedPoints=targetEarnedReversed;old.loyaltyRestoredUsedPoints=targetUsedRestored;if(earnedDelta||restoreDelta){const loyaltyId=serverId('loy');operations.push({op:'put',store:'loyalty',id:loyaltyId,value:{id:loyaltyId,customerId:String(old.customerId),customerName:customer?.name||old.customerName||'',saleId:String(old.id||incoming.saleId),saleNo:old.no||'',returnId:String(ret.id||retOp.id),points:restoreDelta-earnedDelta,earnedPointsReversed:-earnedDelta,usedPointsRestored:restoreDelta,note:'تسوية نقاط تلقائية بسبب مرتجع بيع',type:'sale_return',at:ret.inspectedAt,branchId:old.branchId||null,userId:user?.id||null,userName:user?.name||''}})}}
 if(customerOps.length&&!customerOp)throw Object.assign(new Error('RETURN_CUSTOMER_WRITE_NOT_ALLOWED'),{status:403});if(claimOps.length&&String(old.payment)!=='insurance')throw Object.assign(new Error('RETURN_CLAIM_WRITE_NOT_ALLOWED'),{status:403});
 for(const m of cashOps){if(String(m.value?.type||'')!=='sale_return'||String(m.value?.ref||'')!==`R-${old.no}`||String(m.value?.direction||'')!=='out')throw Object.assign(new Error('RETURN_CASH_MOVE_INVALID'),{status:409})}const actualCash=Finance.money(cashOps.reduce((a,o)=>a+Number(o.value?.amount||0),0));if(Math.abs(actualCash-expectedCash)>Finance.EPS)throw Object.assign(new Error('RETURN_CASH_MOVE_MISMATCH'),{status:409,details:{expected:expectedCash,actual:actualCash}});
 if(expectedCash>0){if(String(old.payment)==='split'&&refundMethod==='original'){const entries=Object.entries(old.splitPayments||{}).filter(([,v])=>Number(v)>0),base=Math.max(0.01,entries.reduce((a,[,v])=>a+Number(v),0));for(const [method,value] of entries){const expected=Finance.money(derived.total*Number(value)/base),actual=Finance.money(cashOps.filter(o=>String(o.value?.method||'')===method).reduce((a,o)=>a+Number(o.value?.amount||0),0));if(Math.abs(actual-expected)>0.03)throw Object.assign(new Error('RETURN_PAYMENT_METHOD_MISMATCH'),{status:409,details:{method,expected,actual}})}}else{const expectedMethod=String(old.payment)==='insurance'&&refundMethod==='original'?'cash':refundMethod==='original'?String(old.payment||'cash'):refundMethod;if(cashOps.some(o=>String(o.value?.method||'')!==expectedMethod))throw Object.assign(new Error('RETURN_PAYMENT_METHOD_MISMATCH'),{status:409,details:{expectedMethod}})}}
 saleOp.value={...old,_serverRevision:saleOp.value?._serverRevision,returnedQtyByLine:derived.returnedQtyByLine,returnedBaseByBatch:used,returnedReceiptByLayer:usedLayers,returnedAmount:Finance.money(Number(old.returnedAmount||0)+derived.total),returnedCost:Finance.money(Number(old.returnedCost||0)+returnedCost),returnedTax:Finance.money(Number(old.returnedTax||0)+derived.tax),returnedDeliveryFee:Finance.money(Number(old.returnedDeliveryFee||0)+derived.deliveryRefund),creditBalance:old.creditBalance,loyaltyReversedEarnedPoints:Number(old.loyaltyReversedEarnedPoints||0),loyaltyRestoredUsedPoints:Number(old.loyaltyRestoredUsedPoints||0),status:derived.fully?'returned':'partial_return',returnedAt:ret.inspectedAt};
 const j=operations.find(o=>o.op==='put'&&o.store==='journal'&&o.value?.type==='sale_return');if(!j)throw Object.assign(new Error('RETURN_JOURNAL_REQUIRED'),{status:409});const loss=String(ret.disposition)==='damaged'||String(ret.disposition)==='expired';j.value.lines=[{accountCode:'4010',account:'مردودات المبيعات',debit:derived.net,credit:0},...(derived.tax>0?[{accountCode:'2100',account:'ضريبة مخرجات مستحقة',debit:derived.tax,credit:0}]:[]),...(derived.deliveryRefund>0?[{accountCode:'4100',account:'إيرادات التوصيل',debit:derived.deliveryRefund,credit:0}]:[]),...settlementCredits,...(loss&&returnedCost>0?[{accountCode:'6100',account:'خسائر التلف والانتهاء',debit:returnedCost,credit:0},{accountCode:'5000',account:'تكلفة البضاعة المباعة',debit:0,credit:returnedCost}]:restored>0?[{accountCode:'1200',account:'المخزون',debit:restored,credit:0},{accountCode:'5000',account:'تكلفة البضاعة المباعة',debit:0,credit:restored}]:[])];j.value.debit=Finance.money(j.value.lines.reduce((a,l)=>a+Number(l.debit||0),0));j.value.credit=Finance.money(j.value.lines.reduce((a,l)=>a+Number(l.credit||0),0));j.value.balanced=Math.abs(j.value.debit-j.value.credit)<0.01;
}

 return {normalizeSaleCatalog,prepareSaleCommercial,prepareInsuranceClaimsCommercial,prepareReturnCommercial};
};

export {};
