import type{DbExecutor}from'../../../core/db/types.js';import{newId}from'../../../core/types/id.js';import type{NotificationContract,NotificationView}from'../contracts/notification-contract.js';
export class PostgresNotificationRepository implements NotificationContract{constructor(private readonly db:DbExecutor){}
async list(t:string,u:string,limit=100){return(await this.db.query<NotificationView>(`SELECT id,title,body,severity,link,read_at::text as "readAt",resolved_at::text as "resolvedAt",created_at::text as "createdAt" FROM notifications WHERE tenant_id=$1 AND resolved_at IS NULL AND (user_id IS NULL OR user_id=$2) ORDER BY created_at DESC LIMIT $3`,[t,u,Math.min(300,Math.max(1,limit))])).rows;}
async unreadCount(t:string,u:string){return Number((await this.db.query<{count:string}>(`SELECT count(*)::text count FROM notifications WHERE tenant_id=$1 AND resolved_at IS NULL AND read_at IS NULL AND (user_id IS NULL OR user_id=$2)`,[t,u])).rows[0]?.count??0);}
async markRead(t:string,u:string,id:string){await this.db.query(`UPDATE notifications SET read_at=now() WHERE tenant_id=$1 AND id=$2 AND resolved_at IS NULL AND (user_id IS NULL OR user_id=$3)`,[t,id,u]);}
async upsertAlert(i:{tenantId:string;dedupeKey:string;title:string;body:string;severity:'info'|'warning'|'danger';link?:string|null}){await this.db.query(`INSERT INTO notifications(id,tenant_id,user_id,title,body,severity,dedupe_key,resolved_at,link) VALUES($1,$2,NULL,$3,$4,$5,$6,NULL,$7) ON CONFLICT(tenant_id,dedupe_key) WHERE dedupe_key IS NOT NULL DO UPDATE SET title=EXCLUDED.title,body=EXCLUDED.body,severity=EXCLUDED.severity,link=EXCLUDED.link,resolved_at=NULL,read_at=CASE WHEN notifications.body IS DISTINCT FROM EXCLUDED.body OR notifications.severity IS DISTINCT FROM EXCLUDED.severity THEN NULL ELSE notifications.read_at END,created_at=CASE WHEN notifications.body IS DISTINCT FROM EXCLUDED.body OR notifications.severity IS DISTINCT FROM EXCLUDED.severity THEN now() ELSE notifications.created_at END`,[newId('ntf'),i.tenantId,i.title,i.body,i.severity,i.dedupeKey,i.link??null]);}
async resolveAlert(t:string,key:string){await this.db.query(`UPDATE notifications SET resolved_at=COALESCE(resolved_at,now()) WHERE tenant_id=$1 AND dedupe_key=$2 AND resolved_at IS NULL`,[t,key]);}
async purgeResolved(days:number){const q=await this.db.query(`DELETE FROM notifications WHERE resolved_at IS NOT NULL AND resolved_at<now()-($1::text||' days')::interval`,[Math.max(7,Math.min(3650,days))]);return q.rowCount??0;}
}
