#!/usr/bin/env node
'use strict';
const {performance}=require('node:perf_hooks');
function percentile(a,p){const s=[...a].sort((x,y)=>x-y);return s[Math.min(s.length-1,Math.floor((s.length-1)*p))]||0}
function run(){const report={version:require('../package.json').version,at:new Date().toISOString(),tests:{}};
 let t=performance.now();const products=Array.from({length:100000},(_,i)=>({id:'p'+i,barcode:String(6223000000000+i),gtin:String(10000000000000+i),name:`Drug ${i}`,active:`Ingredient ${i%500}`,company:`Company ${i%120}`}));const idx=new Map();const search=[];for(const x of products){idx.set(x.barcode,x);idx.set(x.gtin,x);search.push(`${x.name} ${x.barcode} ${x.gtin} ${x.active} ${x.company}`.toLowerCase())}const buildMs=performance.now()-t;
 t=performance.now();let hits=0;const lat=[];for(let i=0;i<50000;i++){const s=performance.now();if(idx.get(String(6223000000000+(i*7919)%100000)))hits++;lat.push(performance.now()-s)}const scanMs=performance.now()-t;report.tests.barcode={ok:hits===50000,products:products.length,hits,buildMs:+buildMs.toFixed(2),scanTotalMs:+scanMs.toFixed(2),lookupP95Ms:+percentile(lat,.95).toFixed(4)};
 t=performance.now();let found=0;for(const q of ['drug 999','ingredient 42','company 77','622300004']){for(let i=0;i<search.length&&found<320;i++)if(search[i].includes(q))found++}const searchMs=performance.now()-t;report.tests.largeData={ok:searchMs<1500,rows:100000,queries:4,firstResults:found,elapsedMs:+searchMs.toFixed(2)};
 const receiptLines=Array.from({length:80},(_,i)=>`<tr><td>Drug ${i}</td><td>1</td><td>10.00</td><td>10.00</td></tr>`).join('');const receipt=`<style>@page{size:80mm auto;margin:2.5mm}</style><table>${receiptLines}</table>`;report.tests.receipt={ok:/size:80mm auto/.test(receipt)&&receiptLines.split('<tr>').length-1===80,paper:'80mm',lines:80};
 const jobs=80,ops=250; t=performance.now();return Promise.all(Array.from({length:jobs},async(_,j)=>{let sum=0;for(let i=0;i<ops;i++){sum+=(idx.get(String(6223000000000+((j*ops+i)%100000)))?.id.length||0);if(i%40===0)await Promise.resolve()}return sum})).then(()=>{const elapsed=performance.now()-t;report.tests.concurrentSimulation={ok:elapsed<1200,jobs,opsPerJob:ops,elapsedMs:+elapsed.toFixed(2)};report.ok=Object.values(report.tests).every(x=>x.ok);console.log(JSON.stringify(report,null,2));if(!report.ok)process.exitCode=1;return report})}
run().catch(e=>{console.error(e);process.exit(1)});
