import{api,post}from'../api/client.js';import{h,money,modal,toast}from'../components/dom.js';import{state}from'../state/store.js';
export async function financePage(){const root=h('div'),head=h('div',{class:'section-head'},h('div',{},h('h2',{},'الذمم والمصروفات'),h('p',{},'تحصيل العملاء • سداد الموردين • المصروفات')),h('div',{class:'section-actions'},h('button',{class:'btn primary','data-act':'pay'},'+ سداد / تحصيل'),h('button',{class:'btn','data-act':'expense'},'+ مصروف'))),body=h('div',{class:'grid two'});root.append(head,body);async function load(){const[o,p,cr,e,c,s]=await Promise.all([api<any>('/api/settlements/obligations'),api<any>('/api/settlements/payments'),api<any>('/api/settlements/credits'),api<any>('/api/expenses'),api<any>('/api/customers'),api<any>('/api/suppliers')]);const names=new Map<string,string>([...c.items,...s.items].map((x:any)=>[x.id,x.name]));body.replaceChildren(card('الذمم المفتوحة',obligations(o.items,names)),card('أرصدة دائنة من المرتجعات',credits(cr.items,names)),card('آخر المدفوعات',payments(p.items,names)),card('المصروفات',expenses(e.items)),card('ملخص',summary(o.items,e.items,cr.items)));}(head.querySelector('[data-act="pay"]')as HTMLButtonElement).onclick=()=>void openPayment(load);(head.querySelector('[data-act="expense"]')as HTMLButtonElement).onclick=()=>void openExpense(load);await load();return root;}
function card(title:string,child:Node){return h('section',{class:'card'},h('h3',{},title),child)}
function obligations(items:any[],names:Map<string,string>){const open=items.filter(x=>Number(x.balance)>0);if(!open.length)return h('div',{class:'empty'},'لا توجد ذمم مفتوحة.');return table(['الطرف','النوع','الرصيد','الحالة'],open.map(x=>[names.get(x.partyId)??x.partyId,x.partyType==='customer'?'عميل':'مورد',money(x.balance),x.status]));}
function credits(items:any[],names:Map<string,string>){const open=items.filter(x=>Number(x.balance)>0);if(!open.length)return h('div',{class:'empty'},'لا توجد أرصدة دائنة.');return table(['الطرف','النوع','الرصيد','المرجع'],open.map(x=>[names.get(x.partyId)??x.partyId,x.partyType==='customer'?'رصيد للعميل':'رصيد لدى المورد',money(x.balance),x.referenceType]));}
function payments(items:any[],names:Map<string,string>){if(!items.length)return h('div',{class:'empty'},'لا توجد مدفوعات بعد.');return table(['الطرف','الحركة','المبلغ','غير موزع'],items.slice(0,30).map(x=>[names.get(x.partyId)??x.partyId,x.direction==='receive'?'تحصيل':'سداد',money(x.amount),money(x.unallocated)]));}
function expenses(items:any[]){if(!items.length)return h('div',{class:'empty'},'لا توجد مصروفات بعد.');return table(['التاريخ','الفئة','البيان','المبلغ'],items.slice(0,30).map(x=>[new Date(x.createdAt).toLocaleString('ar-EG'),x.category,x.description,money(x.amount)]));}
function summary(obs:any[],ex:any[],cr:any[]){const ar=obs.filter(x=>x.partyType==='customer').reduce((s,x)=>s+Number(x.balance||0),0),ap=obs.filter(x=>x.partyType==='supplier').reduce((s,x)=>s+Number(x.balance||0),0),expensesTotal=ex.reduce((s,x)=>s+Number(x.amount||0),0),customerCredits=cr.filter(x=>x.partyType==='customer').reduce((s,x)=>s+Number(x.balance||0),0),supplierCredits=cr.filter(x=>x.partyType==='supplier').reduce((s,x)=>s+Number(x.balance||0),0);return h('div',{class:'list'},line('مديونية العملاء',money(ar)),line('مستحقات الموردين',money(ap)),line('أرصدة مستحقة للعملاء',money(customerCredits)),line('أرصدة لنا لدى الموردين',money(supplierCredits)),line('إجمالي المصروفات',money(expensesTotal)));}
function line(a:string,b:string){return h('div',{class:'list-row'},h('span',{},a),h('strong',{},b))}
function table(headers:string[],rows:(string|number)[][]){const t=h('div',{class:'table-wrap'},h('table',{class:'table'},h('thead',{},h('tr',{},...headers.map(x=>h('th',{},x)))),h('tbody')));for(const r of rows)(t.querySelector('tbody')!).append(h('tr',{},...r.map(x=>h('td',{},String(x)))));return t;}
async function openPayment(done:()=>Promise<void>){const[c,s]=await Promise.all([api<any>('/api/customers'),api<any>('/api/suppliers')]);const type=select('partyType',[['customer','عميل'],['supplier','مورد']]),party=select('partyId',[]),method=select('method',[['cash','نقدي'],['card','بطاقة'],['bank','بنك']]);const fill=()=>{party.replaceChildren();for(const x of(type.value==='customer'?c.items:s.items))party.append(h('option',{value:x.id},x.name));};type.onchange=fill;fill();const body=h('div',{class:'form-grid'},lab('نوع الطرف',type),lab('الطرف',party),lab('طريقة الدفع',method),inp('amount','المبلغ','number','0'),inp('reference','مرجع اختياري'));modal('سداد / تحصيل',body,async form=>{const fd=new FormData(form);await post('/api/settlements/payments',{branchId:state.branch?.id,partyType:fd.get('partyType'),partyId:fd.get('partyId'),method:fd.get('method'),amount:Number(fd.get('amount')),reference:fd.get('reference')});toast('تم تسجيل الحركة');await done();});}
function openExpense(done:()=>Promise<void>){const body=h('div',{class:'form-grid'},inp('category','الفئة','text','تشغيل'),inp('description','البيان'),inp('amount','المبلغ','number','0'),lab('طريقة الدفع',select('method',[['cash','نقدي'],['bank','بنك'],['card','بطاقة']])));modal('تسجيل مصروف',body,async form=>{const fd=new FormData(form);await post('/api/expenses',{branchId:state.branch?.id,category:fd.get('category'),description:fd.get('description'),amount:Number(fd.get('amount')),method:fd.get('method')});toast('تم تسجيل المصروف');await done();});}
function select(name:string,ops:[string,string][]){const s=h('select',{name});for(const[o,l]of ops)s.append(h('option',{value:o},l));return s;}function lab(t:string,e:HTMLElement){return h('label',{class:'field'},h('span',{},t),e)}function inp(n:string,t:string,type='text',value=''){return lab(t,h('input',{name:n,type,value,required:n!=='reference',step:type==='number'?'0.01':undefined,min:type==='number'?'0.01':undefined}));}
