import{api,post}from'../api/client.js';import{h,toast,modal}from'../components/dom.js';import{state}from'../state/store.js';
export async function inventoryPage(){const root=h('div'),head=h('div',{class:'section-head'},h('div',{},h('h2',{},'المخزون'),h('p',{},'الأرصدة والتشغيلات والصلاحية — FEFO')),h('div',{class:'section-actions'},h('button',{class:'btn primary','data-a':'transfer'},'تحويل مخزون'),h('button',{class:'btn','data-a':'count'},'جرد تشغيلة'))),content=h('div');root.append(head,content);async function load(){const branch=state.branch?.id??'';const[balances,batches,products,branches,transfers,counts]=await Promise.all([api<any>(`/api/inventory/balances?branchId=${branch}`),api<any>(`/api/inventory/batches?branchId=${branch}`),api<any>('/api/products?limit=500'),api<any>('/api/organization/branches'),api<any>('/api/inventory/transfers'),api<any>('/api/inventory/counts')]);const names=new Map(products.items.map((p:any)=>[p.id,p.name])),branchNames=new Map(branches.items.map((b:any)=>[b.id,b.name]));content.replaceChildren(h('div',{class:'grid two'},card('أرصدة الأصناف',tableBalances(balances.items,names)),card('التشغيلات',tableBatches(batches.items,names)),card('آخر التحويلات',transfersTable(transfers.items,names,branchNames)),card('آخر الجرد',countsTable(counts.items,names))));(head.querySelector('[data-a="transfer"]')as HTMLButtonElement).onclick=()=>openTransfer(products.items,branches.items,load);(head.querySelector('[data-a="count"]')as HTMLButtonElement).onclick=()=>openCount(batches.items,names,load);}await load();return root;}
function card(t:string,c:Node){return h('section',{class:'card'},h('h3',{},t),c)}
function tableBalances(items:any[],names:Map<any,any>){if(!items.length)return h('div',{class:'empty'},'لا يوجد مخزون بعد.');return simple(['الصنف','الكمية','أقرب صلاحية'],items.map(x=>[names.get(x.productId)??x.productId,String(x.quantity),x.nearestExpiry??'—']));}
function tableBatches(items:any[],names:Map<any,any>){if(!items.length)return h('div',{class:'empty'},'لا توجد تشغيلات بعد.');return simple(['الصنف','التشغيلة','الصلاحية','الكمية','الحالة'],items.map(x=>[names.get(x.productId)??x.productId,x.batchNo??'—',x.expiryDate??'—',String(x.quantity),x.status]));}
function transfersTable(items:any[],names:Map<any,any>,branches:Map<any,any>){if(!items.length)return h('div',{class:'empty'},'لا توجد تحويلات.');return simple(['من','إلى','الأصناف','التاريخ'],items.slice(0,20).map(x=>[branches.get(x.fromBranchId)??x.fromBranchId,branches.get(x.toBranchId)??x.toBranchId,x.lines.map((l:any)=>`${names.get(l.productId)??l.productId} × ${l.quantity}`).join('، '),new Date(x.createdAt).toLocaleString('ar-EG')]));}
function countsTable(items:any[],names:Map<any,any>){if(!items.length)return h('div',{class:'empty'},'لا توجد عمليات جرد.');return simple(['التاريخ','الأصناف','فرق الجرد'],items.slice(0,20).map(x=>[new Date(x.createdAt).toLocaleString('ar-EG'),String(x.lines.length),String(x.lines.reduce((s:number,l:any)=>s+Number(l.difference),0))]));}
function simple(headers:string[],rows:any[][]){const t=h('div',{class:'table-wrap'},h('table',{class:'table'},h('thead',{},h('tr',{},...headers.map(x=>h('th',{},x)))),h('tbody')));for(const r of rows)(t.querySelector('tbody')!).append(h('tr',{},...r.map(x=>h('td',{},String(x)))));return t;}
function openTransfer(products:any[],branches:any[],done:()=>Promise<void>){const others=branches.filter(x=>x.id!==state.branch?.id&&x.active);if(!others.length)return toast('أضف فرعاً آخر من الإعدادات أولاً',true);const body=h('div',{class:'form-grid'},lab('إلى الفرع',sel('toBranchId',others.map((x:any)=>[x.id,x.name]))),lab('الصنف',sel('productId',products.map((x:any)=>[x.id,x.name]))),inp('quantity','الكمية','number','1'));modal('تحويل مخزون',body,async f=>{const d=new FormData(f);await post('/api/inventory/transfers',{fromBranchId:state.branch?.id,toBranchId:d.get('toBranchId'),lines:[{productId:d.get('productId'),quantity:Number(d.get('quantity'))}]});toast('تم تحويل المخزون');await done();});}
function openCount(batches:any[],names:Map<any,any>,done:()=>Promise<void>){const available=batches.filter(x=>Number(x.quantity)>=0);if(!available.length)return toast('لا توجد تشغيلات للجرد',true);const body=h('div',{class:'form-grid'},lab('التشغيلة',sel('batchId',available.map((x:any)=>[x.id,`${names.get(x.productId)??x.productId} — ${x.batchNo??'بدون رقم'} — الحالي ${x.quantity}`]))),inp('counted','الكمية الفعلية','number','0'));modal('جرد تشغيلة',body,async f=>{const d=new FormData(f);await post('/api/inventory/counts',{branchId:state.branch?.id,lines:[{batchId:d.get('batchId'),counted:Number(d.get('counted'))}]});toast('تم اعتماد الجرد');await done();});}
function lab(t:string,e:HTMLElement){return h('label',{class:'field'},h('span',{},t),e)}function inp(n:string,t:string,type='text',value=''){return lab(t,h('input',{name:n,type,value,required:true,min:type==='number'?'0':undefined,step:type==='number'?'0.01':undefined}))}function sel(n:string,ops:any[]){const s=h('select',{name:n});for(const[o,l]of ops)s.append(h('option',{value:o},l));return s;}
