import{api,post}from'../api/client.js';
import{h,money,toast}from'../components/dom.js';
import{state}from'../state/store.js';

type Product={id:string;name:string;barcode:string|null;sellingPrice:number;costPrice?:number;taxRate:number;requiresPrescription?:boolean};
type CartLine={product:Product;quantity:number};
type LoyaltyState={points:number;pointValue:number;minRedeemPoints:number;maxRedeemPercent:number;enabled:boolean}|null;
const can=(p:string)=>!!state.user&&(state.user.permissions.includes('*')||state.user.permissions.includes(p));

export async function posPage(){
  const root=h('div'),cart:CartLine[]=[];let products:Product[]=[],customers:any[]=[],prescriptions:any[]=[],loyalty:LoyaltyState=null,lastAttemptFingerprint='',lastAttemptKey='';
  const canProfit=can('profit.view'),canLoyaltyRead=can('loyalty.read'),canRedeem=can('loyalty.redeem'),canCreditOverride=can('sales.credit.override'),canSettlementRead=can('settlements.read');
  const head=h('div',{class:'section-head'},h('div',{},h('h2',{},'نقطة البيع'),h('p',{},'بيع ذري • FEFO • سلامة دوائية • عروض • ولاء'))),layout=h('div',{class:'pos-layout'}),productsCard=h('section',{class:'card pos-products'}),cartCard=h('section',{class:'card'}),search=h('input',{class:'search-input',placeholder:'ابحث بالاسم أو الباركود'}),grid=h('div',{class:'product-grid',style:'margin-top:12px'}),cartBox=h('div',{class:'cart'}),customer=h('select'),payment=h('select'),prescription=h('select'),rxField=label('الروشتة',prescription),invoiceDiscount=h('input',{type:'number',min:'0',step:'0.01',value:'0'}),loyaltyPoints=h('input',{type:'number',min:'0',step:'1',value:'0'}),loyaltyInfo=h('small',{class:'muted'},'اختر عميلاً لعرض نقاط الولاء'),loyaltyField=label('استبدال نقاط الولاء',h('div',{},loyaltyPoints,loyaltyInfo)),creditOverride=h('input',{placeholder:'سبب تجاوز حد الائتمان عند موافقة المدير'}),creditInfo=h('small',{class:'muted'},''),creditField=label('تجاوز حد الائتمان',h('div',{},creditOverride,creditInfo)),totals=h('div',{class:'totals'}),profitHint=h('div',{class:'notice',style:'display:none;margin-top:10px'}),submit=h('button',{class:'btn primary block'},'اعتماد البيع');
  customer.append(h('option',{value:''},'عميل نقدي'));payment.append(h('option',{value:'cash'},'نقدي'),h('option',{value:'card'},'بطاقة'),h('option',{value:'credit'},'آجل'));prescription.append(h('option',{value:''},'اختر روشتة عند الحاجة'));loyaltyField.style.display=canLoyaltyRead?'grid':'none';loyaltyPoints.disabled=!canRedeem;creditField.style.display='none';
  productsCard.append(h('div',{class:'toolbar'},search),grid);cartCard.append(h('h3',{},'الفاتورة الحالية'),cartBox,h('div',{class:'form-grid',style:'margin-top:12px'},label('العميل',customer),label('الدفع',payment),rxField,label('خصم الفاتورة',invoiceDiscount),loyaltyField,creditField),totals,profitHint,submit);layout.append(productsCard,cartCard);root.append(head,layout);

  const data=await api<any>('/api/products?limit=500');products=data.items;customers=(await api<any>('/api/customers')).items;prescriptions=(await api<any>('/api/clinical/sale-prescriptions').catch(()=>({items:[]}))).items;
  for(const c of customers)customer.append(h('option',{value:c.id},c.name));for(const rx of prescriptions)prescription.append(h('option',{value:rx.id},`روشتة ${String(rx.id).slice(-6)}${rx.expiresAt?' — '+new Date(rx.expiresAt).toLocaleDateString('ar-EG'):''}`));

  function renderProducts(){const q=search.value.trim().toLowerCase();const shown=products.filter(p=>!q||p.name.toLowerCase().includes(q)||(p.barcode??'').toLowerCase().includes(q)).slice(0,60);grid.replaceChildren(...shown.map(p=>h('button',{class:'product-tile',onClick:()=>{const line=cart.find(x=>x.product.id===p.id);if(line)line.quantity++;else cart.push({product:p,quantity:1});renderCart();}},h('b',{},p.name),h('small',{},p.barcode??'بدون باركود'),h('div',{class:'tile-meta'},h('strong',{},money(p.sellingPrice)),p.requiresPrescription?h('span',{class:'tag warning'},'Rx'):null))));if(!shown.length)grid.replaceChildren(h('div',{class:'empty'},'لا توجد نتائج'));}
  function estimatedLoyaltyDiscount(amount:number){if(!loyalty?.enabled)return 0;const requested=Math.max(0,Math.floor(Number(loyaltyPoints.value||0))),maxBySale=Math.floor((amount*(loyalty.maxRedeemPercent/100))/loyalty.pointValue);return Math.min(requested,Math.floor(loyalty.points),Math.max(0,maxBySale))*loyalty.pointValue;}
  function renderCart(){
    cartBox.replaceChildren(...cart.map((line,i)=>h('div',{class:'cart-row'},h('div',{},h('b',{},line.product.name),h('small',{},money(line.product.sellingPrice*line.quantity))),h('div',{class:'qty-controls'},h('button',{type:'button',onClick:()=>{line.quantity=Math.max(1,line.quantity-1);renderCart();}},'−'),h('span',{},String(line.quantity)),h('button',{type:'button',onClick:()=>{line.quantity++;renderCart();}},'+'),h('button',{type:'button',onClick:()=>{cart.splice(i,1);renderCart();}},'×')))));
    const subtotal=cart.reduce((s,l)=>s+l.product.sellingPrice*l.quantity,0),tax=cart.reduce((s,l)=>s+l.product.sellingPrice*l.quantity*(l.product.taxRate/100),0),discount=Number(invoiceDiscount.value||0),beforeLoyalty=Math.max(0,subtotal+tax-discount),loyaltyDiscount=estimatedLoyaltyDiscount(beforeLoyalty),total=Math.max(0,beforeLoyalty-loyaltyDiscount),needsRx=cart.some(l=>l.product.requiresPrescription);
    rxField.style.display=needsRx?'grid':'none';if(!needsRx)prescription.value='';
    totals.replaceChildren(row('قبل الضريبة',money(subtotal)),row('الضريبة',money(tax)),row('خصم يدوي',money(discount)),...(loyaltyDiscount>0?[row('خصم نقاط تقريبي',money(loyaltyDiscount))]:[]),h('div',{class:'total-row grand'},h('span',{},'الإجمالي التقريبي'),h('span',{},money(total))));
    if(loyalty){const requested=Math.max(0,Math.floor(Number(loyaltyPoints.value||0))),hint=loyalty.enabled?`الرصيد: ${Math.floor(loyalty.points)} نقطة • قيمة النقطة ${money(loyalty.pointValue)} • حد أدنى ${loyalty.minRedeemPoints} • أقصى ${loyalty.maxRedeemPercent}% من الفاتورة`:'برنامج الولاء متوقف حالياً';loyaltyInfo.textContent=requested>0?`${hint} — الخصم النهائي يحتسب على الخادم عند الاعتماد.`:hint;}
    const hasCosts=cart.length>0&&cart.every(l=>typeof l.product.costPrice==='number');if(canProfit&&hasCosts){const cost=cart.reduce((s,l)=>s+Number(l.product.costPrice)*l.quantity,0),margin=Math.max(0,subtotal-discount-loyaltyDiscount-cost);profitHint.style.display='block';profitHint.textContent=`هامش تقريبي قبل الضريبة والعروض التلقائية: ${money(margin)} — المرجع النهائي هو الفاتورة المعتمدة.`;}else{profitHint.style.display='none';profitHint.textContent='';}
  }
  async function loadCredit(){creditInfo.textContent='';creditField.style.display=canCreditOverride&&payment.value==='credit'?'grid':'none';if(!customer.value||payment.value!=='credit'||!canSettlementRead)return;try{const r=await api<any>(`/api/party360/customers/${encodeURIComponent(customer.value)}`);creditInfo.textContent=`المستحق الحالي ${money(Number(r.outstanding??0))} • المتاح من الحد ${money(Number(r.availableCredit??0))}`;}catch{creditInfo.textContent='';}}
  async function loadLoyalty(){loyalty=null;loyaltyPoints.value='0';if(!customer.value||!canLoyaltyRead){loyaltyInfo.textContent='اختر عميلاً لعرض نقاط الولاء';renderCart();return;}try{const r=await api<any>(`/api/loyalty/${encodeURIComponent(customer.value)}?limit=10`);loyalty={points:Number(r.account.points??0),pointValue:Number(r.rule.pointValue??0.01),minRedeemPoints:Number(r.rule.minRedeemPoints??100),maxRedeemPercent:Number(r.rule.maxRedeemPercent??20),enabled:r.rule.enabled!==false};loyaltyPoints.max=String(Math.max(0,Math.floor(loyalty.points)));}catch{loyaltyInfo.textContent='تعذر تحميل رصيد الولاء';}renderCart();}

  search.oninput=renderProducts;invoiceDiscount.oninput=renderCart;loyaltyPoints.oninput=renderCart;customer.onchange=()=>{if(customer.value){const rx=prescriptions.find(x=>x.customerId===customer.value);if(rx)prescription.value=rx.id;}void loadLoyalty();void loadCredit();};payment.onchange=()=>void loadCredit();
  submit.onclick=async()=>{if(!cart.length)return toast('أضف صنفاً واحداً على الأقل',true);if(cart.some(x=>x.product.requiresPrescription)&&!prescription.value)return toast('الفاتورة تحتوي صنفاً يتطلب روشتة',true);const requestedPoints=Math.max(0,Math.floor(Number(loyaltyPoints.value||0)));if(requestedPoints>0&&!customer.value)return toast('استبدال النقاط يتطلب اختيار عميل',true);try{const payload={branchId:state.branch?.id,customerId:customer.value||null,payment:payment.value,prescriptionId:prescription.value||null,invoiceDiscount:Number(invoiceDiscount.value||0),loyaltyPointsToRedeem:requestedPoints,creditOverrideReason:creditOverride.value.trim()||undefined,lines:cart.map(x=>({productId:x.product.id,quantity:x.quantity}))},fingerprint=JSON.stringify(payload);if(fingerprint!==lastAttemptFingerprint){lastAttemptFingerprint=fingerprint;lastAttemptKey=crypto.randomUUID();}const sale=await post<any>('/api/sales',{...payload,idempotencyKey:lastAttemptKey});toast(`تم اعتماد ${sale.number}${sale.loyaltyPointsRedeemed?` — استُبدل ${sale.loyaltyPointsRedeemed} نقطة`:''}${sale.loyaltyPointsEarned?` — اكتسب ${sale.loyaltyPointsEarned} نقطة`:''}${sale.profit!=null?` — الربح ${money(sale.profit)}`:''}`);lastAttemptFingerprint='';lastAttemptKey='';cart.splice(0);invoiceDiscount.value='0';prescription.value='';loyaltyPoints.value='0';creditOverride.value='';await loadLoyalty();await loadCredit();renderCart();}catch(e:any){toast(e.message??'تعذر اعتماد البيع',true)}};
  renderProducts();renderCart();return root;
}
function label(text:string,control:HTMLElement){return h('label',{class:'field'},h('span',{},text),control)}
function row(a:string,b:string){return h('div',{class:'total-row'},h('span',{},a),h('span',{},b));}
