import{api,post}from'../api/client.js';import{h,money,modal,toast}from'../components/dom.js';
export async function pricingPage(){const root=h('div'),head=h('div',{class:'section-head'},h('div',{},h('h2',{},'الأسعار والعروض'),h('p',{},'عروض تلقائية • مركز تحديث الأسعار')),h('div',{class:'section-actions'},h('button',{class:'btn primary','data-a':'offer'},'+ عرض'),h('button',{class:'btn','data-a':'update'},'+ تحديث سعر'))),grid=h('div',{class:'grid two'});root.append(head,grid);async function load(){const[o,u,p]=await Promise.all([api<any>('/api/pricing/offers'),api<any>('/api/pricing/updates'),api<any>('/api/products?limit=500')]),names=new Map(p.items.map((x:any)=>[x.id,x.name]));grid.replaceChildren(box('العروض',offers(o.items,names)),box('تحديثات الأسعار',updates(u.items,names,load)));(head.querySelector('[data-a="offer"]')as HTMLButtonElement).onclick=()=>openOffer(p.items,load);(head.querySelector('[data-a="update"]')as HTMLButtonElement).onclick=()=>openUpdate(p.items,load);}await load();return root;}
function box(t:string,c:Node){return h('section',{class:'card'},h('h3',{},t),c)}
function offers(items:any[],names:Map<any,any>){if(!items.length)return h('div',{class:'empty'},'لا توجد عروض.');return table(['الاسم','الصنف','الخصم','الحد الأدنى','الحالة'],items.map(x=>[x.name,x.productId?names.get(x.productId)??x.productId:'كل الأصناف',x.kind==='percent'?`${x.value}%`:money(x.value),x.minQty,x.active?'نشط':'متوقف']));}
function updates(items:any[],names:Map<any,any>,done:()=>Promise<void>){if(!items.length)return h('div',{class:'empty'},'لا توجد تحديثات أسعار.');const wrap=h('div',{class:'table-wrap'},h('table',{class:'table'},h('thead',{},h('tr',{},...['الصنف','قديم','جديد','المصدر','الحالة',''].map(x=>h('th',{},x)))),h('tbody')));for(const x of items){const btn=x.status==='pending'?h('button',{class:'btn sm',onClick:async()=>{await post(`/api/pricing/updates/${x.id}/apply`,{});toast('تم تطبيق السعر');await done();}},'تطبيق'):h('span',{class:'muted'},'—');(wrap.querySelector('tbody')!).append(h('tr',{},h('td',{},names.get(x.productId)??x.productId),h('td',{},money(x.oldPrice)),h('td',{},money(x.newPrice)),h('td',{},x.source??'—'),h('td',{},x.status),h('td',{},btn)));}return wrap;}
function table(hs:string[],rows:any[][]){const t=h('div',{class:'table-wrap'},h('table',{class:'table'},h('thead',{},h('tr',{},...hs.map(x=>h('th',{},x)))),h('tbody')));for(const r of rows)(t.querySelector('tbody')!).append(h('tr',{},...r.map(x=>h('td',{},String(x)))));return t;}
function openOffer(products:any[],done:()=>Promise<void>){const body=h('div',{class:'form-grid'},inp('name','اسم العرض'),lab('الصنف',sel('productId',[['','كل الأصناف'],...products.map((x:any)=>[x.id,x.name])])),lab('نوع الخصم',sel('kind',[['percent','نسبة %'],['fixed','قيمة ثابتة لكل وحدة']])),inp('value','قيمة الخصم','number','0'),inp('minQty','أقل كمية','number','1'),inp('endsAt','تاريخ النهاية','datetime-local'));modal('إضافة عرض',body,async f=>{const d=new FormData(f);await post('/api/pricing/offers',{name:d.get('name'),productId:d.get('productId')||null,kind:d.get('kind'),value:Number(d.get('value')),minQty:Number(d.get('minQty')),endsAt:d.get('endsAt')||null});toast('تم إنشاء العرض');await done();});}
function openUpdate(products:any[],done:()=>Promise<void>){const body=h('div',{class:'form-grid'},lab('الصنف',sel('productId',products.map((x:any)=>[x.id,x.name]))),inp('newPrice','السعر الجديد','number','0'),inp('source','المصدر'),inp('note','ملاحظة'));modal('تحديث سعر',body,async f=>{const d=new FormData(f);await post('/api/pricing/updates',{productId:d.get('productId'),newPrice:Number(d.get('newPrice')),source:d.get('source'),note:d.get('note')});toast('تم إنشاء تحديث السعر للمراجعة');await done();});}
function inp(n:string,t:string,type='text',value=''){return lab(t,h('input',{name:n,type,value,required:['name','value','minQty','newPrice'].includes(n),step:type==='number'?'0.01':undefined,min:type==='number'?'0':undefined}))}function lab(t:string,e:HTMLElement){return h('label',{class:'field'},h('span',{},t),e)}function sel(n:string,ops:any[]){const s=h('select',{name:n});for(const[o,l]of ops)s.append(h('option',{value:o},l));return s;}
