import{api,post}from'../api/client.js';import{h,money,modal,toast}from'../components/dom.js';
export async function productsPage(){
  const root=h('div'),head=h('div',{class:'section-head'},h('div',{},h('h2',{},'الأصناف'),h('p',{},'تعريف المنتجات والأسعار والباركود + قاعدة أدوية مركزية نظيفة')),h('div',{class:'section-actions'},h('button',{class:'btn',id:'masterBtn'},'قاعدة الأدوية المركزية'),h('button',{class:'btn primary'},'+ صنف جديد')));
  const card=h('section',{class:'card'}),search=h('input',{class:'search-input',placeholder:'بحث بالاسم أو الباركود أو SKU'}),table=h('div',{class:'table-wrap'});card.append(h('div',{class:'toolbar'},search),table);
  const master=h('section',{class:'card hidden',style:'margin-top:13px'},h('div',{class:'section-head'},h('div',{},h('h3',{},'قاعدة الأدوية المركزية'),h('p',{id:'masterCount'},'بحث بالاسم أو المادة الفعالة أو الشركة أو الباركود'))),h('div',{class:'toolbar'},h('input',{class:'search-input',id:'masterSearch',placeholder:'اكتب حرفين أو أكثر…'}),h('button',{class:'btn',id:'masterRefresh'},'بحث')),h('div',{id:'masterResults',class:'table-wrap'}));
  root.append(head,card,master);
  async function load(){const data=await api<any>(`/api/products?q=${encodeURIComponent(search.value)}`);table.replaceChildren(data.items?.length?renderTable(data.items,data.costVisible===true):h('div',{class:'empty'},'لا توجد أصناف بعد.'));}
  async function loadMaster(){const q=(master.querySelector('#masterSearch') as HTMLInputElement).value.trim();const result=master.querySelector('#masterResults')!;result.replaceChildren(h('div',{class:'empty'},'جاري البحث…'));try{const data=await api<any>(`/api/drug-master?q=${encodeURIComponent(q)}&limit=50`);(master.querySelector('#masterCount')!).textContent=`${new Intl.NumberFormat('ar-EG').format(Number(data.count??0))} دواء مرجعي — ابحث بالاسم أو المادة الفعالة أو الشركة أو الباركود`;result.replaceChildren(data.items?.length?masterTable(data.items,load):h('div',{class:'empty'},'لا توجد نتائج.'));}catch(e:any){result.replaceChildren(h('div',{class:'auth-error'},e.message??'تعذر البحث'));}}
  search.oninput=()=>void load();(head.querySelector('.primary') as HTMLButtonElement).onclick=()=>openAdd(load);(head.querySelector('#masterBtn') as HTMLButtonElement).onclick=()=>{master.classList.toggle('hidden');if(!master.classList.contains('hidden'))void loadMaster();};(master.querySelector('#masterRefresh') as HTMLButtonElement).onclick=()=>void loadMaster();(master.querySelector('#masterSearch') as HTMLInputElement).onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();void loadMaster();}};await load();return root;
}
function renderTable(items:any[],showCost:boolean){const headers=['الصنف','الباركود','سعر البيع',...(showCost?['التكلفة']:[]),'الضريبة','روشتة','الحالة'];const t=h('table',{class:'table'},h('thead',{},h('tr',{},...headers.map(x=>h('th',{},x)))),h('tbody'));for(const p of items)t.tBodies[0]!.append(h('tr',{},h('td',{},p.name),h('td',{},p.barcode??'—'),h('td',{},money(p.sellingPrice)),...(showCost?[h('td',{},money(p.costPrice))]:[]),h('td',{},`${p.taxRate??0}%`),h('td',{},p.requiresPrescription?'مطلوبة':'لا'),h('td',{},h('span',{class:`tag ${p.active?'success':''}`},p.active?'نشط':'موقوف'))));return t;}
function masterTable(items:any[],done:()=>Promise<void>){const t=h('table',{class:'table'},h('thead',{},h('tr',{},...['الدواء','المادة الفعالة','الشركة','الشكل','السعر الرسمي','روشتة','إضافة'].map(x=>h('th',{},x)))),h('tbody'));for(const d of items){const btn=h('button',{class:'btn sm primary',onClick:()=>openAdopt(d,done)},'إضافة للصيدلية');t.tBodies[0]!.append(h('tr',{},h('td',{},h('strong',{},d.nameAr),h('small',{class:'muted',style:'display:block'},[d.barcode,d.gtin].filter(Boolean).join(' • ')||'بدون باركود')),h('td',{},(d.activeIngredients??[]).join(' + ')||'—'),h('td',{},d.manufacturer??'—'),h('td',{},[d.strength,d.dosageForm].filter(Boolean).join(' • ')||'—'),h('td',{},d.officialPrice==null?'—':money(d.officialPrice)),h('td',{},d.requiresPrescription?'مطلوبة':'لا'),h('td',{},btn)));}return t;}
function openAdopt(d:any,done:()=>Promise<void>){const body=h('div',{class:'form-grid'},h('div',{class:'auth-note span-2'},`${d.nameAr}${d.manufacturer?' — '+d.manufacturer:''}`),num('sellingPrice','سعر البيع',d.officialPrice??0),num('costPrice','التكلفة',0),num('reorderLevel','حد إعادة الطلب',0),num('taxRate','الضريبة %',0));modal('إضافة الدواء إلى أصناف الصيدلية',body,async form=>{const fd=new FormData(form);await post(`/api/drug-master/${d.id}/adopt`,{sellingPrice:Number(fd.get('sellingPrice')),costPrice:Number(fd.get('costPrice')),reorderLevel:Number(fd.get('reorderLevel')),taxRate:Number(fd.get('taxRate'))});toast('تم إنشاء الصنف من قاعدة الأدوية المركزية');await done();});}
function openAdd(done:()=>Promise<void>){const rx=h('input',{name:'requiresPrescription',type:'checkbox'}),body=h('div',{class:'form-grid'},field('name','اسم الصنف','text',true),field('barcode','الباركود'),field('sku','SKU'),field('sellingPrice','سعر البيع','number',true),field('costPrice','التكلفة','number',true),field('taxRate','الضريبة %','number'),field('reorderLevel','حد إعادة الطلب','number'),h('label',{class:'check'},rx,h('span',{},'يتطلب روشتة')),field('controlledClass','تصنيف الدواء الخاضع للرقابة'));modal('إضافة صنف',body,async form=>{const fd=new FormData(form);await post('/api/products',{name:fd.get('name'),barcode:fd.get('barcode'),sku:fd.get('sku'),sellingPrice:Number(fd.get('sellingPrice')),costPrice:Number(fd.get('costPrice')),taxRate:Number(fd.get('taxRate')||0),reorderLevel:Number(fd.get('reorderLevel')||0),requiresPrescription:fd.get('requiresPrescription')==='on',controlledClass:fd.get('controlledClass')||null});toast('تم إنشاء الصنف');await done();});}
function field(name:string,label:string,type='text',required=false){return h('label',{class:'field'},h('span',{},label),h('input',{name,type,required,step:type==='number'?'0.01':undefined,min:type==='number'?'0':undefined}));}
function num(name:string,label:string,value:number){return h('label',{class:'field'},h('span',{},label),h('input',{name,type:'number',required:true,step:'0.01',min:'0',value:String(value)}));}
