import{api,put,post}from'../api/client.js';import{h,toast,modal}from'../components/dom.js';

type Prefs=Record<string,any>;
export async function settingsPage(){
 const[s,branches]=await Promise.all([api<any>('/api/settings'),api<any>('/api/organization/branches')]);
 const p:Prefs=s?.preferences??{};syncLocalUiPrefs(p);
 const root=h('div',{class:'settings-page legacy-rich-settings'}),head=h('div',{class:'section-head'},h('div',{},h('h2',{},'الإعدادات'),h('p',{},'إعدادات تشغيل كاملة للصيدلية — مظهر، طباعة، سياسات، جهاز، فروع ونسخ احتياطي')));
 const tabs=h('div',{class:'settings-tabs owner-family-tabs'}),body=h('div',{class:'settings-body'});root.append(head,tabs,body);
 const sections:[string,string,string,()=>HTMLElement][]=[
  ['appearance','المظهر','الثيم والخط والقائمة',()=>appearanceSection(p)],
  ['general','الصيدلية','الهوية والبيانات',()=>generalSection(s)],
  ['printing','الطباعة','هوية الفاتورة والطابعة',()=>printingSection(s,p)],
  ['operation','التشغيل','البيع والمخزون والولاء والرقابة',()=>operationSection(p)],
  ['device','الجهاز','POS والباركود والاختبارات',()=>deviceSection(p)],
  ['branches','الفروع','إدارة الفروع',()=>branchesSection(branches)],
  ['backup','النسخ','النسخ والاستعادة',()=>backupSection()],
 ];
 let active=sessionStorage.getItem('elhafez-settings-tab')||'appearance';
 const render=()=>{tabs.replaceChildren(...sections.map(([id,label,sub])=>h('button',{class:`settings-tab ${active===id?'active':''}`,type:'button',onClick:()=>{active=id;sessionStorage.setItem('elhafez-settings-tab',id);render();}},h('b',{},label),h('small',{},sub))));const sec=sections.find(x=>x[0]===active)??sections[0]!;body.replaceChildren(sec[3]());};render();return root;

 function appearanceSection(pref:Prefs){
  const appearance=select('appearance','الثيم',[['light','فاتح'],['comfort','هادئ / مريح'],['dark','داكن']],pref.appearance??'light'),accent=colorField('accentColor','لون الهوية المساعد',pref.accentColor??'#19b6b6'),side=select('sidebarMode','القائمة الجانبية',[['fixed','ثابتة'],['auto','مصغرة وتفتح عند المرور'],['hidden','Drawer — زر الثلاث شرطات']],pref.sidebarMode??'fixed'),animations=sw('animations','الحركات والانتقالات','يمكن إيقافها على الأجهزة الضعيفة',pref.animations!==false);
  const fonts:[string,string,string][]=[['cairo','Cairo','واضح وقوي'],['tajawal','Tajawal','خفيف وحديث'],['almarai','Almarai','مريح للقراءة'],['noto','Noto Sans Arabic','متوازن وسريع'],['plex','IBM Plex Sans Arabic','إداري ونظيف']];
  const fontSel=select('fontFamily','الخط العربي',fonts.map(x=>[x[0],`${x[1]} — ${x[2]}`] as [string,string]),pref.fontFamily??'noto'),scale=select('fontScale','حجم خط الواجهة',[['0.87','13px'],['0.93','14px'],['1','15px'],['1.07','16px'],['1.13','17px'],['1.2','18px'],['1.27','19px'],['1.33','20px']],String(pref.fontScale??1));
  const preview=h('div',{class:'appearance-preview'},h('strong',{},'الحافظ للصيدليات 123456'),h('small',{},'معاينة فورية للمظهر قبل الحفظ'));
  const form=h('form',{class:'settings-panel'},sectionTitle('المظهر والخط','تحكم في شكل النظام بدون لمس أي Business Module'),h('div',{class:'form-grid'},appearance.wrap,accent,fontSel.wrap,scale.wrap,side.wrap),h('div',{class:'settings-switches'},animations.wrap),preview,saveBar());
  const live=()=>{applyUiPrefs({appearance:appearance.input.value,accentColor:(accent.querySelector('input')as HTMLInputElement).value,fontFamily:fontSel.input.value,fontScale:Number(scale.input.value),sidebarMode:side.input.value,animations:animations.input.checked});};appearance.input.onchange=live;(accent.querySelector('input')as HTMLInputElement).oninput=live;fontSel.input.onchange=live;scale.input.onchange=live;side.input.onchange=live;animations.input.onchange=live;
  form.onsubmit=e=>savePrefs(e,{appearance:appearance.input.value,accentColor:(accent.querySelector('input')as HTMLInputElement).value,fontFamily:fontSel.input.value,fontScale:Number(scale.input.value),sidebarMode:side.input.value,animations:animations.input.checked},true);return form;
 }
 function generalSection(data:any){const form=h('form',{class:'settings-panel form-grid'},sectionTitle('بيانات الصيدلية','البيانات الرسمية المستخدمة داخل النظام والمستندات'),f('pharmacyName','اسم الصيدلية',data?.pharmacyName??'',true),f('phone','الهاتف',data?.phone??''),f('whatsapp','واتساب',data?.whatsapp??''),f('email','البريد الإلكتروني',data?.email??'',false,'email'),f('address','العنوان',data?.address??''),f('taxNumber','الرقم الضريبي',data?.taxNumber??''),f('commercialRegistration','السجل التجاري',data?.commercialRegistration??''),saveBar());form.onsubmit=e=>saveGeneral(e,form);return form;}
 function printingSection(data:any,pref:Prefs){
  const logoPreview=h('div',{class:'receipt-logo-preview'},pref.receiptLogoData?h('img',{src:pref.receiptLogoData,alt:'شعار الصيدلية'}):h('span',{},String((pref.receiptBusinessName||data?.pharmacyName||'ص')).charAt(0))),logo=h('input',{type:'file',accept:'image/png,image/jpeg,image/webp'}),clear=h('button',{class:'btn sm',type:'button'},'إزالة الشعار');let logoData=String(pref.receiptLogoData??'');
  logo.onchange=async()=>{const file=logo.files?.[0];if(!file)return;if(file.size>700_000){logo.value='';return toast('حجم الشعار كبير؛ الحد 700KB',true)}logoData=await fileData(file);logoPreview.replaceChildren(h('img',{src:logoData,alt:'شعار الصيدلية'}));};clear.onclick=()=>{logoData='';logo.value='';logoPreview.replaceChildren(h('span',{},String((pref.receiptBusinessName||data?.pharmacyName||'ص')).charAt(0)));};
  const paper=select('paperSize','مقاس المستند الافتراضي',[['A4','A4'],['80mm','حراري 80mm'],['58mm','حراري 58mm']],pref.paperSize??'A4');
  const showPhone=sw('receiptShowPhone','إظهار الهاتف','في رأس الفاتورة',pref.receiptShowPhone!==false),showAddress=sw('receiptShowAddress','إظهار العنوان','في رأس الفاتورة',pref.receiptShowAddress!==false),showTax=sw('receiptShowTaxNumber','إظهار الرقم الضريبي','في رأس الفاتورة',pref.receiptShowTaxNumber!==false),showCr=sw('receiptShowCommercialRegister','إظهار السجل التجاري','في رأس الفاتورة',pref.receiptShowCommercialRegister!==false);
  const form=h('form',{class:'settings-panel'},sectionTitle('هوية الفاتورة والطباعة','الصيدلية تتحكم في هويتها، بينما منطق المستندات يظل داخل Documents Module'),h('div',{class:'receipt-logo-editor'},logoPreview,h('div',{},h('label',{class:'btn sm file-action'},'رفع شعار',logo),clear,h('small',{class:'muted'},'PNG / JPG / WEBP حتى 700KB'))),h('div',{class:'form-grid'},f('receiptBusinessName','اسم النشاط على الفاتورة',pref.receiptBusinessName||data?.pharmacyName||''),f('receiptPhone','هاتف الطباعة',pref.receiptPhone||data?.phone||''),f('receiptAddress','عنوان الطباعة',pref.receiptAddress||data?.address||''),f('receiptTaxNumber','الرقم الضريبي',pref.receiptTaxNumber||data?.taxNumber||''),f('receiptCommercialRegister','السجل التجاري',pref.receiptCommercialRegister||data?.commercialRegistration||''),f('receiptExtraInfo','بيانات إضافية',pref.receiptExtraInfo||''),paper.wrap,textarea('invoiceFooter','تذييل الإيصال',data?.invoiceFooter??'')),h('div',{class:'settings-switches'},showPhone.wrap,showAddress.wrap,showTax.wrap,showCr.wrap),saveBar());
  form.onsubmit=async e=>{e.preventDefault();const fd=new FormData(form);await saveAll({invoiceFooter:String(fd.get('invoiceFooter')??''),preferences:{receiptBusinessName:String(fd.get('receiptBusinessName')??''),receiptPhone:String(fd.get('receiptPhone')??''),receiptAddress:String(fd.get('receiptAddress')??''),receiptTaxNumber:String(fd.get('receiptTaxNumber')??''),receiptCommercialRegister:String(fd.get('receiptCommercialRegister')??''),receiptExtraInfo:String(fd.get('receiptExtraInfo')??''),receiptLogoData:logoData,paperSize:paper.input.value,receiptShowPhone:showPhone.input.checked,receiptShowAddress:showAddress.input.checked,receiptShowTaxNumber:showTax.input.checked,receiptShowCommercialRegister:showCr.input.checked}});};return form;
 }
 function operationSection(pref:Prefs){
  const payment=select('defaultPaymentMethod','طريقة الدفع الافتراضية',[['cash','نقدي'],['card','بطاقة'],['credit','آجل']],pref.defaultPaymentMethod??'cash'),expiry=nf('expiryWarningDays','تنبيه الصلاحية قبل (يوم)',pref.expiryWarningDays??90,7,730),coverage=nf('lowStockCoverageDays','هدف تغطية الشراء (يوم)',pref.lowStockCoverageDays??14,1,120),safety=nf('reorderSafetyDays','مخزون أمان إضافي (يوم)',pref.reorderSafetyDays??3,0,60),earn=nf('loyaltyEarnEvery','نقطة لكل مبلغ',pref.loyaltyEarnEvery??10,.01,1000000,.01),redeem=nf('loyaltyRedeemValue','قيمة النقطة',pref.loyaltyRedeemValue??.1,0,1000000,.01),variance=nf('shiftVarianceTolerance','حد فرق النقدية المقبول',pref.shiftVarianceTolerance??1,0,1000000,.01);
  const profit=sw('showProfitInPos','إظهار الربح في نقطة البيع','حسب صلاحية المستخدم',pref.showProfitInPos!==false),focus=sw('autoFocusPosSearch','تركيز تلقائي على البحث والباركود','جاهز للمسح فور فتح POS',pref.autoFocusPosSearch!==false),confirmSale=sw('confirmBeforeSale','تأكيد قبل اعتماد البيع','خطوة أمان إضافية',pref.confirmBeforeSale===true),reorder=sw('reorderSuggestionsEnabled','اقتراح إعادة الطلب تلقائيًا','يبني توصيات من حركة البيع والمخزون',pref.reorderSuggestionsEnabled!==false),brief=sw('dailyBriefEnabled','الملخص التنفيذي اليومي','يعرض ما يحتاج قرارًا اليوم',pref.dailyBriefEnabled!==false),low=sw('notifyLowStock','تنبيهات النواقص','إظهار نقص المخزون',pref.notifyLowStock!==false),ex=sw('notifyExpiry','تنبيهات الصلاحية','إظهار القريب والمنتهي',pref.notifyExpiry!==false),reqShift=sw('requireOpenShift','منع البيع النقدي بدون وردية','حماية الخزينة وحركة النقد',pref.requireOpenShift!==false),blind=sw('blindShiftClose','إغلاق أعمى للوردية','الكاشير يدخل الفعلي قبل رؤية المتوقع',pref.blindShiftClose!==false),shortage=sw('shortageNotebookEnabled','تفعيل كشكول النواقص','طلبات العملاء والأصناف غير المتوفرة',pref.shortageNotebookEnabled!==false),capture=sw('customerRequestCaptureEnabled','ربط النقص بطلب العميل','اسم/هاتف العميل للمتابعة',pref.customerRequestCaptureEnabled!==false),autoShort=sw('autoCreateShortageFromPos','تسجيل النقص من POS بسرعة','زر مباشر عندما لا يجد الكاشير الصنف',pref.autoCreateShortageFromPos!==false);
  const form=h('form',{class:'settings-panel'},sectionTitle('سياسات التشغيل','الإعدادات تحدد السياسة، والتنفيذ الفعلي يظل داخل الموديول المختص'),h('div',{class:'form-grid'},payment.wrap,expiry,coverage,safety,earn,redeem,variance),h('h4',{class:'settings-subtitle'},'نقطة البيع والرقابة'),h('div',{class:'settings-switches'},profit.wrap,focus.wrap,confirmSale.wrap,reqShift.wrap,blind.wrap),h('h4',{class:'settings-subtitle'},'الأتمتة والتنبيهات'),h('div',{class:'settings-switches'},reorder.wrap,brief.wrap,low.wrap,ex.wrap,shortage.wrap,capture.wrap,autoShort.wrap),saveBar());
  form.onsubmit=e=>savePrefs(e,{defaultPaymentMethod:payment.input.value,expiryWarningDays:value(expiry),lowStockCoverageDays:value(coverage),reorderSafetyDays:value(safety),loyaltyEarnEvery:value(earn),loyaltyRedeemValue:value(redeem),shiftVarianceTolerance:value(variance),showProfitInPos:profit.input.checked,autoFocusPosSearch:focus.input.checked,confirmBeforeSale:confirmSale.input.checked,reorderSuggestionsEnabled:reorder.input.checked,dailyBriefEnabled:brief.input.checked,notifyLowStock:low.input.checked,notifyExpiry:ex.input.checked,requireOpenShift:reqShift.input.checked,blindShiftClose:blind.input.checked,shortageNotebookEnabled:shortage.input.checked,customerRequestCaptureEnabled:capture.input.checked,autoCreateShortageFromPos:autoShort.input.checked});return form;
 }
 function deviceSection(pref:Prefs){const name=f('deviceName','اسم جهاز نقطة البيع',pref.deviceName??'POS-01'),width=select('receiptWidth','عرض ورق الإيصال',[['80','80 mm'],['58','58 mm']],pref.receiptWidth??'80'),tax=select('taxIntegrationMode','تكامل الإيصال الإلكتروني',[['disabled','غير مفعّل'],['ready','جاهز للربط عبر Backend']],pref.taxIntegrationMode??'disabled'),printer=h('button',{class:'pilot-card',type:'button'},h('b',{},'▤ إيصال اختبار'),h('small',{},'فحص الطابعة الحرارية')),scanner=h('button',{class:'pilot-card',type:'button'},h('b',{},'⌁ قارئ الباركود'),h('small',{},'فحص المسح وEnter')),performance=h('button',{class:'pilot-card',type:'button'},h('b',{},'↯ اختبار الأداء'),h('small',{},'فحص سريع للجهاز'));printer.onclick=()=>printTest(pref);scanner.onclick=()=>scannerTest();performance.onclick=()=>performanceTest();const form=h('form',{class:'settings-panel'},sectionTitle('الجهاز والتكاملات','إعداد الجهاز الحالي واختبارات التسليم التجاري'),h('div',{class:'form-grid'},name,width.wrap,tax.wrap),h('div',{class:'notice'},'قارئ الباركود يعمل Keyboard Wedge. الإعداد هنا لا يضع منطق الجهاز داخل المبيعات.'),h('div',{class:'pilot-grid'},printer,scanner,performance),saveBar());form.onsubmit=e=>savePrefs(e,{deviceName:(name.querySelector('input')as HTMLInputElement).value,receiptWidth:width.input.value,taxIntegrationMode:tax.input.value});return form;}
 function branchesSection(data:any){const branchName=h('input',{placeholder:'اسم الفرع الجديد'}),add=h('button',{class:'btn primary',type:'button'},'إضافة فرع'),list=h('div',{class:'list'},...(data.items??[]).map((b:any)=>h('div',{class:'list-row'},h('span',{},h('b',{},b.name),h('small',{class:'muted'},b.id)),h('span',{class:`tag ${b.active?'success':''}`},b.active?'نشط':'موقوف'))));add.onclick=async()=>{try{if(branchName.value.trim().length<2)return toast('اكتب اسم الفرع',true);const b=await post<any>('/api/organization/branches',{name:branchName.value.trim()});list.append(h('div',{class:'list-row'},h('span',{},h('b',{},b.name)),h('span',{class:'tag success'},'نشط')));branchName.value='';toast('تمت إضافة الفرع');}catch(e:any){toast(e.message,true)}};return h('section',{class:'settings-panel'},sectionTitle('الفروع','الفروع تظل داخل Organization Module والإعدادات مجرد نقطة وصول'),list,h('div',{class:'toolbar',style:'margin-top:14px'},branchName,add));}
 function backupSection(){const go=h('button',{class:'action-card',type:'button'},h('b',{},'فتح النسخ الاحتياطي الآمن'),h('small',{},'إنشاء، فحص واستعادة نسخة مشفرة')),sec=h('button',{class:'action-card',type:'button'},h('b',{},'فتح سجل التدقيق'),h('small',{},'راجع أثر عمليات الاستعادة والتغييرات الحساسة'));go.onclick=()=>window.dispatchEvent(new CustomEvent('elhafez:navigate',{detail:'backup'}));sec.onclick=()=>window.dispatchEvent(new CustomEvent('elhafez:navigate',{detail:'audit'}));return h('section',{class:'settings-panel'},sectionTitle('البيانات والنسخ الاحتياطي','النسخ والاستعادة تظل داخل Backup Module المستقل'),h('div',{class:'settings-action-grid'},go,sec),h('div',{class:'notice success'},'لا يوجد JSON عشوائي أو مسح مباشر من الإعدادات. الاستعادة تمر بفحص النسخة وسلامة البيانات.'));}
 async function saveGeneral(e:Event,form:HTMLFormElement){e.preventDefault();const fd=new FormData(form);await saveAll(Object.fromEntries(fd.entries()));}
 async function savePrefs(e:Event,partial:Record<string,unknown>,apply=false){e.preventDefault();await saveAll({preferences:partial});if(apply){syncLocalUiPrefs(partial);applyUiPrefs(partial);}}
 async function saveAll(partial:any){try{const current=await api<any>('/api/settings'),prefs={...(current.preferences??{}),...(partial.preferences??{})};await put('/api/settings',{pharmacyName:partial.pharmacyName??current.pharmacyName,phone:partial.phone??current.phone,address:partial.address??current.address,email:partial.email??current.email,whatsapp:partial.whatsapp??current.whatsapp,taxNumber:partial.taxNumber??current.taxNumber,commercialRegistration:partial.commercialRegistration??current.commercialRegistration,invoiceFooter:partial.invoiceFooter??current.invoiceFooter,preferences:prefs});syncLocalUiPrefs(prefs);applyUiPrefs(prefs);toast('تم حفظ الإعدادات');}catch(err:any){toast(err.message??'تعذر حفظ الإعدادات',true)}}
}
function sectionTitle(title:string,sub:string){return h('div',{class:'settings-panel-head span-2'},h('div',{},h('h3',{},title),h('p',{},sub)));}
function saveBar(){return h('div',{class:'settings-save span-2'},h('button',{class:'btn primary',type:'submit'},'حفظ التغييرات'));}
function f(n:string,l:string,v:string,r=false,type='text'){return h('label',{class:'field'},h('span',{},l),h('input',{name:n,value:v,required:r,type}));}
function nf(n:string,l:string,v:number,min:number,max:number,step=1){return h('label',{class:'field'},h('span',{},l),h('input',{name:n,type:'number',value:String(v),min:String(min),max:String(max),step:String(step)}));}
function value(el:HTMLElement){return Number((el.querySelector('input')as HTMLInputElement).value);}
function textarea(n:string,l:string,v:string){return h('label',{class:'field span-2'},h('span',{},l),h('textarea',{name:n,rows:4,value:v}));}
function colorField(n:string,l:string,v:string){return h('label',{class:'field'},h('span',{},l),h('input',{name:n,type:'color',value:v}));}
function select(n:string,l:string,items:[string,string][],value:string){const input=h('select',{name:n});for(const[v,label]of items)input.append(h('option',{value:v,selected:v===value},label));return{input,wrap:h('label',{class:'field'},h('span',{},l),input)} as any;}
function sw(n:string,title:string,sub:string,checked:boolean){const input=h('input',{type:'checkbox',name:n,checked}),wrap=h('label',{class:'settings-switch'},h('span',{},h('b',{},title),h('small',{},sub)),h('span',{class:'switch-ui'},input,h('i')));return{input,wrap};}
function fileData(file:File){return new Promise<string>((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result??''));r.onerror=()=>rej(r.error);r.readAsDataURL(file);});}
function syncLocalUiPrefs(p:any){try{localStorage.setItem('elhafez-ui-prefs',JSON.stringify({...JSON.parse(localStorage.getItem('elhafez-ui-prefs')||'{}'),...p}));}catch{}}
function applyUiPrefs(p:any){const d=document.documentElement;d.dataset.theme=p.appearance??d.dataset.theme??'light';d.dataset.sidebarMode=p.sidebarMode??d.dataset.sidebarMode??'fixed';d.dataset.animations=p.animations===false?'off':'on';d.dataset.font=p.fontFamily??d.dataset.font??'noto';if(p.accentColor)d.style.setProperty('--accent',String(p.accentColor));if(p.fontScale)d.style.setProperty('--font-scale',String(p.fontScale));}
function printTest(pref:any){const w=window.open('','_blank');if(!w)return toast('اسمح بفتح نافذة الطباعة',true);w.document.write(`<html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>إيصال اختبار</title><style>body{font-family:Arial;padding:20px;text-align:center}hr{border:0;border-top:1px dashed #888}</style></head><body><h3>${pref.receiptBusinessName||'Elhafez Pharmacy'}</h3><p>إيصال اختبار الطابعة</p><hr><p>1234567890</p><small>إذا ظهر هذا الإيصال بوضوح فالطابعة جاهزة.</small></body></html>`);w.document.close();setTimeout(()=>{w.focus();w.print();},100);}
function scannerTest(){const input=h('input',{placeholder:'امسح أي باركود هنا',autofocus:true,autocomplete:'off'}),out=h('div',{class:'notice'},'في انتظار القراءة…');modal('اختبار قارئ الباركود',h('div',{},h('label',{class:'field'},h('span',{},'الكود المقروء'),input),out));const started={at:0};input.onkeydown=(e:KeyboardEvent)=>{if(!started.at)started.at=performance.now();if(e.key==='Enter'){e.preventDefault();const ms=Math.max(1,Math.round(performance.now()-started.at));out.textContent=input.value.trim().length>=4?`تم التقاط ${input.value.trim()} خلال ${ms} ms`:'الكود قصير أو لم تتم القراءة بصورة سليمة';started.at=0;input.select();}};setTimeout(()=>input.focus(),50);}
function performanceTest(){const t=performance.now(),rows=Array.from({length:40000},(_,i)=>String(6223000000000+i)),idx=new Set(rows);let hit=0;for(let i=0;i<12000;i++)if(idx.has(String(6223000000000+(i*37)%40000)))hit++;const ms=Math.round(performance.now()-t);modal('اختبار الأداء',h('div',{class:`notice ${ms<1000?'success':'warning'}`},`${hit}/12000 عملية بحث محلية خلال ${ms} ms. هذا اختبار للجهاز فقط وليس بديلاً عن اختبار السيرفر وقاعدة البيانات.`));}
